//
// AccountUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Today&#39;s usage counters. Snapshot reflects the in-memory rollup; counts reset at UTC midnight. */
public struct AccountUsage: Codable, JSONEncodable, Hashable {

    /** Always `today` for the current-day rollup. */
    public var date: String
    public var apiCalls: Int?
    public var emailSends: Int?
    public var notesCount: Int?
    public var sheetsCount: Int?
    public var slidesCount: Int?
    public var filesCount: Int?
    public var tasksCount: Int?

    public init(date: String, apiCalls: Int? = nil, emailSends: Int? = nil, notesCount: Int? = nil, sheetsCount: Int? = nil, slidesCount: Int? = nil, filesCount: Int? = nil, tasksCount: Int? = nil) {
        self.date = date
        self.apiCalls = apiCalls
        self.emailSends = emailSends
        self.notesCount = notesCount
        self.sheetsCount = sheetsCount
        self.slidesCount = slidesCount
        self.filesCount = filesCount
        self.tasksCount = tasksCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case apiCalls = "api_calls"
        case emailSends = "email_sends"
        case notesCount = "notes_count"
        case sheetsCount = "sheets_count"
        case slidesCount = "slides_count"
        case filesCount = "files_count"
        case tasksCount = "tasks_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(apiCalls, forKey: .apiCalls)
        try container.encodeIfPresent(emailSends, forKey: .emailSends)
        try container.encodeIfPresent(notesCount, forKey: .notesCount)
        try container.encodeIfPresent(sheetsCount, forKey: .sheetsCount)
        try container.encodeIfPresent(slidesCount, forKey: .slidesCount)
        try container.encodeIfPresent(filesCount, forKey: .filesCount)
        try container.encodeIfPresent(tasksCount, forKey: .tasksCount)
    }
}

