//
// AccountListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** &#x60;GET /v1/accounts&#x60; returns &#x60;{accounts_by_platform, total_accounts}&#x60; on production today. Schema kept open until the consumers migrate to a flat &#x60;accounts&#x60; array.  */
public struct AccountListResponse: Codable, JSONEncodable, Hashable {

    public var accountsByPlatform: [String: AnyCodable]?
    public var totalAccounts: Int?
    public var accounts: [AnyCodable]?

    public init(accountsByPlatform: [String: AnyCodable]? = nil, totalAccounts: Int? = nil, accounts: [AnyCodable]? = nil) {
        self.accountsByPlatform = accountsByPlatform
        self.totalAccounts = totalAccounts
        self.accounts = accounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountsByPlatform = "accounts_by_platform"
        case totalAccounts = "total_accounts"
        case accounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountsByPlatform, forKey: .accountsByPlatform)
        try container.encodeIfPresent(totalAccounts, forKey: .totalAccounts)
        try container.encodeIfPresent(accounts, forKey: .accounts)
    }
}

