//
// AgentListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AgentListResponse: Codable, JSONEncodable, Hashable {

    public var agents: [Agent]?
    public var hasMore: Bool?
    public var total: Int?
    public var totalCount: Int?

    public init(agents: [Agent]?, hasMore: Bool? = nil, total: Int? = nil, totalCount: Int? = nil) {
        self.agents = agents
        self.hasMore = hasMore
        self.total = total
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agents
        case hasMore
        case total
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(agents, forKey: .agents)
        try container.encodeIfPresent(hasMore, forKey: .hasMore)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(totalCount, forKey: .totalCount)
    }
}

