//
// AmbiguousAccountError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returned when the caller&#39;s request matches more than one connected account and no &#x60;accountId&#x60; query param disambiguates which one to target. The &#x60;accounts&#x60; array enumerates the candidates so the client can prompt the user to pick.  */
public struct AmbiguousAccountError: Codable, JSONEncodable, Hashable {

    /** Human-readable error message. */
    public var error: String
    /** Machine-readable error code. Stable across releases for the canonical codes (`ambiguous_account`, `no_notes_provider`, `note_not_found`). Absent for generic errors.  */
    public var code: String?
    public var accounts: [AccountChoice]?

    public init(error: String, code: String? = nil, accounts: [AccountChoice]? = nil) {
        self.error = error
        self.code = code
        self.accounts = accounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case code
        case accounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(accounts, forKey: .accounts)
    }
}

