//
// AppFileContentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AppFileContentResponse: Codable, JSONEncodable, Hashable {

    public var path: String
    public var content: String?

    public init(path: String, content: String? = nil) {
        self.path = path
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encodeIfPresent(content, forKey: .content)
    }
}

