//
// Attachment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Attachment: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var title: String
    public var mimeType: String?
    public var url: String
    public var size: Int64?

    public init(id: String? = nil, title: String, mimeType: String? = nil, url: String, size: Int64? = nil) {
        self.id = id
        self.title = title
        self.mimeType = mimeType
        self.url = url
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case mimeType = "mime_type"
        case url
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(mimeType, forKey: .mimeType)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(size, forKey: .size)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Attachment: Identifiable {}
