//
// BlockType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Discriminator for block types. The structure of &#x60;content&#x60; varies by type (e.g. &#x60;paragraph&#x60; carries &#x60;richText&#x60;; &#x60;code&#x60; carries &#x60;richText&#x60; + &#x60;language&#x60;; &#x60;image&#x60; carries &#x60;url&#x60; + &#x60;caption&#x60; + &#x60;altText&#x60;).  */
public enum BlockType: String, Codable, CaseIterable {
    case paragraph = "paragraph"
    case heading1 = "heading_1"
    case heading2 = "heading_2"
    case heading3 = "heading_3"
    case bulletedListItem = "bulleted_list_item"
    case numberedListItem = "numbered_list_item"
    case toDo = "to_do"
    case toggle = "toggle"
    case code = "code"
    case quote = "quote"
    case callout = "callout"
    case divider = "divider"
    case image = "image"
    case video = "video"
    case file = "file"
    case embed = "embed"
    case table = "table"
    case tableRow = "table_row"
    case columnList = "column_list"
    case column = "column"
    case equation = "equation"
    case breadcrumb = "breadcrumb"
    case tableOfContents = "table_of_contents"
}
