//
// BulkDeleteEmailsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Soft-deletes by default (moves to provider trash). Set &#x60;permanent: true&#x60; to hard-delete.  */
public struct BulkDeleteEmailsRequest: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    public var messageIds: [String]
    public var permanent: Bool?

    public init(accountId: String? = nil, messageIds: [String], permanent: Bool? = nil) {
        self.accountId = accountId
        self.messageIds = messageIds
        self.permanent = permanent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case messageIds
        case permanent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(messageIds, forKey: .messageIds)
        try container.encodeIfPresent(permanent, forKey: .permanent)
    }
}

