//
// BulkFilesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Partial-success envelope for bulk delete/move. */
public struct BulkFilesResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool
    public var affectedCount: Int
    public var fileIds: [String]
    public var failed: [BulkFilesResponseFailedInner]

    public init(success: Bool, affectedCount: Int, fileIds: [String], failed: [BulkFilesResponseFailedInner]) {
        self.success = success
        self.affectedCount = affectedCount
        self.fileIds = fileIds
        self.failed = failed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case affectedCount
        case fileIds
        case failed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(affectedCount, forKey: .affectedCount)
        try container.encode(fileIds, forKey: .fileIds)
        try container.encode(failed, forKey: .failed)
    }
}

