//
// BulkArchiveRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BulkArchiveRequest: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    public var messageIds: [String]

    public init(accountId: String? = nil, messageIds: [String]) {
        self.accountId = accountId
        self.messageIds = messageIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case messageIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(messageIds, forKey: .messageIds)
    }
}

