//
// CalendarProviderInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Metadata about one registered calendar provider. */
public struct CalendarProviderInfo: Codable, JSONEncodable, Hashable {

    /** Stable provider id (e.g. `google-calendar`, `native-calendar`). */
    public var id: String
    public var name: String
    public var displayName: String?
    public var description: String?
    /** `true` for built-in providers (the native calendar). */
    public var isSystem: Bool?

    public init(id: String, name: String, displayName: String? = nil, description: String? = nil, isSystem: Bool? = nil) {
        self.id = id
        self.name = name
        self.displayName = displayName
        self.description = description
        self.isSystem = isSystem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case displayName = "display_name"
        case description
        case isSystem = "is_system"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isSystem, forKey: .isSystem)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CalendarProviderInfo: Identifiable {}
