//
// CalendarCapabilitiesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CalendarCapabilitiesResponse: Codable, JSONEncodable, Hashable {

    public var accountId: String
    public var providerId: String
    /** Per-account feature gate. The renderer reads these to enable/ disable form fields (recurrence pickers, attendee inputs, etc.) based on what the underlying provider supports.  */
    public var capabilities: [String: AnyCodable]

    public init(accountId: String, providerId: String, capabilities: [String: AnyCodable]) {
        self.accountId = accountId
        self.providerId = providerId
        self.capabilities = capabilities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case providerId = "provider_id"
        case capabilities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(providerId, forKey: .providerId)
        try container.encode(capabilities, forKey: .capabilities)
    }
}

