//
// CallRecording.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CallRecording: Codable, JSONEncodable, Hashable {

    public var id: String
    public var callId: String?
    public var status: String?
    public var startedAt: Date?
    public var endedAt: Date?
    public var url: String?
    public var metadata: [String: AnyCodable]?

    public init(id: String, callId: String? = nil, status: String? = nil, startedAt: Date? = nil, endedAt: Date? = nil, url: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.id = id
        self.callId = callId
        self.status = status
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.url = url
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case callId
        case status
        case startedAt
        case endedAt
        case url
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(callId, forKey: .callId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(endedAt, forKey: .endedAt)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CallRecording: Identifiable {}
