//
// ChannelMembershipRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body for join/leave operations. */
public struct ChannelMembershipRequest: Codable, JSONEncodable, Hashable {

    public var accountId: String?

    public init(accountId: String? = nil) {
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

