//
// ChangePasswordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChangePasswordRequest: Codable, JSONEncodable, Hashable {

    /** Required when the account already has a password set; omit on first-set. */
    public var currentPassword: String?
    public var newPassword: String

    public init(currentPassword: String? = nil, newPassword: String) {
        self.currentPassword = currentPassword
        self.newPassword = newPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentPassword
        case newPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currentPassword, forKey: .currentPassword)
        try container.encode(newPassword, forKey: .newPassword)
    }
}

