//
// ChatUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatUser: Codable, JSONEncodable, Hashable {

    public var id: String
    public var provider: String?
    public var accountId: String?
    public var name: String
    public var realName: String?
    public var email: String?
    public var avatar: String?
    public var isBot: Bool
    public var isActive: Bool

    public init(id: String, provider: String? = nil, accountId: String? = nil, name: String, realName: String? = nil, email: String? = nil, avatar: String? = nil, isBot: Bool, isActive: Bool) {
        self.id = id
        self.provider = provider
        self.accountId = accountId
        self.name = name
        self.realName = realName
        self.email = email
        self.avatar = avatar
        self.isBot = isBot
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case provider
        case accountId
        case name
        case realName
        case email
        case avatar
        case isBot
        case isActive
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(realName, forKey: .realName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(avatar, forKey: .avatar)
        try container.encode(isBot, forKey: .isBot)
        try container.encode(isActive, forKey: .isActive)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ChatUser: Identifiable {}
