//
// ClientRegistrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ClientRegistrationRequest: Codable, JSONEncodable, Hashable {

    public enum TokenEndpointAuthMethod: String, Codable, CaseIterable {
        case _none = "none"
        case clientSecretBasic = "client_secret_basic"
        case clientSecretPost = "client_secret_post"
    }
    public static let redirectUrisRule = ArrayRule(minItems: nil, maxItems: 10, uniqueItems: false)
    public var clientName: String
    public var redirectUris: [String]
    public var grantTypes: [String]?
    public var responseTypes: [String]?
    /** Space-separated scope list. Defaults to `read:*`. */
    public var scope: String?
    public var tokenEndpointAuthMethod: TokenEndpointAuthMethod? = ._none
    public var clientUri: String?
    public var logoUri: String?
    public var policyUri: String?
    public var tosUri: String?

    public init(clientName: String, redirectUris: [String], grantTypes: [String]? = nil, responseTypes: [String]? = nil, scope: String? = nil, tokenEndpointAuthMethod: TokenEndpointAuthMethod? = ._none, clientUri: String? = nil, logoUri: String? = nil, policyUri: String? = nil, tosUri: String? = nil) {
        self.clientName = clientName
        self.redirectUris = redirectUris
        self.grantTypes = grantTypes
        self.responseTypes = responseTypes
        self.scope = scope
        self.tokenEndpointAuthMethod = tokenEndpointAuthMethod
        self.clientUri = clientUri
        self.logoUri = logoUri
        self.policyUri = policyUri
        self.tosUri = tosUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientName = "client_name"
        case redirectUris = "redirect_uris"
        case grantTypes = "grant_types"
        case responseTypes = "response_types"
        case scope
        case tokenEndpointAuthMethod = "token_endpoint_auth_method"
        case clientUri = "client_uri"
        case logoUri = "logo_uri"
        case policyUri = "policy_uri"
        case tosUri = "tos_uri"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientName, forKey: .clientName)
        try container.encode(redirectUris, forKey: .redirectUris)
        try container.encodeIfPresent(grantTypes, forKey: .grantTypes)
        try container.encodeIfPresent(responseTypes, forKey: .responseTypes)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(tokenEndpointAuthMethod, forKey: .tokenEndpointAuthMethod)
        try container.encodeIfPresent(clientUri, forKey: .clientUri)
        try container.encodeIfPresent(logoUri, forKey: .logoUri)
        try container.encodeIfPresent(policyUri, forKey: .policyUri)
        try container.encodeIfPresent(tosUri, forKey: .tosUri)
    }
}

