//
// CommentMutationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for &#x60;POST&#x60; and &#x60;PATCH&#x60; on a comment. */
public struct CommentMutationResponse: Codable, JSONEncodable, Hashable {

    public var comment: Comment
    public var success: Bool

    public init(comment: Comment, success: Bool) {
        self.comment = comment
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comment, forKey: .comment)
        try container.encode(success, forKey: .success)
    }
}

