//
// CommentListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommentListResponse: Codable, JSONEncodable, Hashable {

    public var comments: [Comment]
    public var total: Int

    public init(comments: [Comment], total: Int) {
        self.comments = comments
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comments
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comments, forKey: .comments)
        try container.encode(total, forKey: .total)
    }
}

