//
// CommentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Single-comment response (&#x60;GET …/comments/:commentId&#x60;). */
public struct CommentResponse: Codable, JSONEncodable, Hashable {

    public var comment: Comment

    public init(comment: Comment) {
        self.comment = comment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comment, forKey: .comment)
    }
}

