//
// ConnectionAccountListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** &#x60;GET /v1/connections/user&#x60; returns &#x60;{connections, user_id}&#x60; (the per-provider connected-account list). Schema kept open pending a normalize-to-&#x60;accounts&#x60; migration.  */
public struct ConnectionAccountListResponse: Codable, JSONEncodable, Hashable {

    public var connections: [AnyCodable]?
    public var userId: String?
    public var accounts: [AnyCodable]?

    public init(connections: [AnyCodable]? = nil, userId: String? = nil, accounts: [AnyCodable]? = nil) {
        self.connections = connections
        self.userId = userId
        self.accounts = accounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connections
        case userId = "user_id"
        case accounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(connections, forKey: .connections)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(accounts, forKey: .accounts)
    }
}

