//
// ContactListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContactListResponse: Codable, JSONEncodable, Hashable {

    public var contacts: [Contact]
    public var totalResults: Int?
    public var updatedAt: Date?

    public init(contacts: [Contact], totalResults: Int? = nil, updatedAt: Date? = nil) {
        self.contacts = contacts
        self.totalResults = totalResults
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contacts
        case totalResults = "total_results"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contacts, forKey: .contacts)
        try container.encodeIfPresent(totalResults, forKey: .totalResults)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

