//
// ContactCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContactCategory: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var color: String?
    public var description: String?
    public var organizationId: String?

    public init(id: String, name: String, color: String? = nil, description: String? = nil, organizationId: String? = nil) {
        self.id = id
        self.name = name
        self.color = color
        self.description = description
        self.organizationId = organizationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case color
        case description
        case organizationId = "organization_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(organizationId, forKey: .organizationId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ContactCategory: Identifiable {}
