//
// CoreAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Renderer-curated \&quot;core action\&quot; entry. These are the keyboard + command-palette surfaced actions; superset of the platform-tagged agent actions. Schema kept open since the platform metadata varies by category.  */
public struct CoreAction: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String?
    public var description: String?
    public var platform: String?
    public var category: String?
    public var icon: String?
    public var metadata: [String: AnyCodable]?

    public init(id: String, name: String? = nil, description: String? = nil, platform: String? = nil, category: String? = nil, icon: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.platform = platform
        self.category = category
        self.icon = icon
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case platform
        case category
        case icon
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CoreAction: Identifiable {}
