//
// CreateNoteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateNoteRequest: Codable, JSONEncodable, Hashable {

    public var title: String
    public var content: String?
    public var icon: String?
    public var coverImage: String?
    public var parentId: String?
    public var properties: [String: AnyCodable]?
    /** Optional override for the target connected account. May also be passed as a `?accountId=` query param.  */
    public var accountId: String?
    /** Optional provider id (alternative to `accountId` when only one account exists for the provider). May also be passed as a `?provider=` query param.  */
    public var provider: String?

    public init(title: String, content: String? = nil, icon: String? = nil, coverImage: String? = nil, parentId: String? = nil, properties: [String: AnyCodable]? = nil, accountId: String? = nil, provider: String? = nil) {
        self.title = title
        self.content = content
        self.icon = icon
        self.coverImage = coverImage
        self.parentId = parentId
        self.properties = properties
        self.accountId = accountId
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case content
        case icon
        case coverImage
        case parentId
        case properties
        case accountId
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(coverImage, forKey: .coverImage)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(properties, forKey: .properties)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(provider, forKey: .provider)
    }
}

