//
// CreateAgentMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAgentMessageRequest: Codable, JSONEncodable, Hashable {

    public var role: String
    public var content: String
    public var metadata: [String: AnyCodable]?

    public init(role: String, content: String, metadata: [String: AnyCodable]? = nil) {
        self.role = role
        self.content = content
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case content
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
        try container.encode(content, forKey: .content)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

