//
// CreateFolderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateFolderRequest: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    public var name: String
    public var parentId: String?
    public var workspaceId: String?
    public var organizationId: String?

    public init(accountId: String? = nil, name: String, parentId: String? = nil, workspaceId: String? = nil, organizationId: String? = nil) {
        self.accountId = accountId
        self.name = name
        self.parentId = parentId
        self.workspaceId = workspaceId
        self.organizationId = organizationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case name
        case parentId
        case workspaceId
        case organizationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
        try container.encodeIfPresent(organizationId, forKey: .organizationId)
    }
}

