//
// CreateCallRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCallRequest: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var workspaceId: String?
    public var roomId: String?
    public var metadata: [String: AnyCodable]?

    public init(title: String? = nil, workspaceId: String? = nil, roomId: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.title = title
        self.workspaceId = workspaceId
        self.roomId = roomId
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case workspaceId
        case roomId
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
        try container.encodeIfPresent(roomId, forKey: .roomId)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

