//
// CreateMeetingRoomRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMeetingRoomRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var workspaceId: String?

    public init(name: String, workspaceId: String? = nil) {
        self.name = name
        self.workspaceId = workspaceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case workspaceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
    }
}

