//
// CreateSheetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateSheetRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var description: String?
    public var data: [String: AnyCodable]?
    public var rowCount: Int?
    public var columnCount: Int?
    /** Optional override for the target connected account. May also be passed as `?accountId=`.  */
    public var accountId: String?
    public var provider: String?

    public init(name: String, description: String? = nil, data: [String: AnyCodable]? = nil, rowCount: Int? = nil, columnCount: Int? = nil, accountId: String? = nil, provider: String? = nil) {
        self.name = name
        self.description = description
        self.data = data
        self.rowCount = rowCount
        self.columnCount = columnCount
        self.accountId = accountId
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case data
        case rowCount
        case columnCount
        case accountId
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(rowCount, forKey: .rowCount)
        try container.encodeIfPresent(columnCount, forKey: .columnCount)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(provider, forKey: .provider)
    }
}

