//
// CreateOrganizationInvitationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateOrganizationInvitationRequest: Codable, JSONEncodable, Hashable {

    public enum Role: String, Codable, CaseIterable {
        case owner = "owner"
        case admin = "admin"
        case billingAdmin = "billing_admin"
        case member = "member"
    }
    public var email: String
    public var role: Role
    /** Optional — the invitee will also be added to this workspace on accept. Defaults to the org's default workspace.  */
    public var workspaceId: String?

    public init(email: String, role: Role, workspaceId: String? = nil) {
        self.email = email
        self.role = role
        self.workspaceId = workspaceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case role
        case workspaceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(role, forKey: .role)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
    }
}

