//
// CreateNote400Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum CreateNote400Response: Codable, JSONEncodable, Hashable {
    case typeAmbiguousAccountError(AmbiguousAccountError)
    case typeApiError(ApiError)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAmbiguousAccountError(let value):
            try container.encode(value)
        case .typeApiError(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AmbiguousAccountError.self) {
            self = .typeAmbiguousAccountError(value)
        } else if let value = try? container.decode(ApiError.self) {
            self = .typeApiError(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of CreateNote400Response"))
        }
    }
}

