//
// CreateBlockRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateBlockRequest: Codable, JSONEncodable, Hashable {

    public var type: BlockType
    public var content: BlockContent
    /** Parent block id for nested blocks. */
    public var parentId: String?
    public var position: Int
    public var properties: [String: AnyCodable]?

    public init(type: BlockType, content: BlockContent, parentId: String? = nil, position: Int, properties: [String: AnyCodable]? = nil) {
        self.type = type
        self.content = content
        self.parentId = parentId
        self.position = position
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case content
        case parentId
        case position
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(content, forKey: .content)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(position, forKey: .position)
        try container.encodeIfPresent(properties, forKey: .properties)
    }
}

