//
// CreateRowRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateRowRequest: Codable, JSONEncodable, Hashable {

    /** Optional zero-based insert position. Omit to append at the end.  */
    public var index: Int?
    public var cells: [String: AnyCodable]

    public init(index: Int? = nil, cells: [String: AnyCodable]) {
        self.index = index
        self.cells = cells
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case cells
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encode(cells, forKey: .cells)
    }
}

