//
// CreateDraftRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateDraftRequest: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    public var to: [String]?
    public var cc: [String]?
    public var bcc: [String]?
    public var subject: String?
    public var body: String?
    public var html: Bool?
    public var attachments: [AttachmentInput]?
    /** Provider thread id — set when this draft is a reply, so the sent message lands inside the parent thread.  */
    public var threadId: String?
    public var inReplyTo: String?
    public var references: [String]?

    public init(accountId: String? = nil, to: [String]? = nil, cc: [String]? = nil, bcc: [String]? = nil, subject: String? = nil, body: String? = nil, html: Bool? = nil, attachments: [AttachmentInput]? = nil, threadId: String? = nil, inReplyTo: String? = nil, references: [String]? = nil) {
        self.accountId = accountId
        self.to = to
        self.cc = cc
        self.bcc = bcc
        self.subject = subject
        self.body = body
        self.html = html
        self.attachments = attachments
        self.threadId = threadId
        self.inReplyTo = inReplyTo
        self.references = references
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case to
        case cc
        case bcc
        case subject
        case body
        case html
        case attachments
        case threadId
        case inReplyTo
        case references
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(to, forKey: .to)
        try container.encodeIfPresent(cc, forKey: .cc)
        try container.encodeIfPresent(bcc, forKey: .bcc)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(html, forKey: .html)
        try container.encodeIfPresent(attachments, forKey: .attachments)
        try container.encodeIfPresent(threadId, forKey: .threadId)
        try container.encodeIfPresent(inReplyTo, forKey: .inReplyTo)
        try container.encodeIfPresent(references, forKey: .references)
    }
}

