//
// DMAttachRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DMAttachRequest: Codable, JSONEncodable, Hashable {

    /** Attachment kind (`image`, `file`, `audio`, `video`, etc.). */
    public var kind: String
    public var url: String
    public var filename: String?
    public var sizeBytes: Int64?
    public var mimeType: String?
    public var thumbnailUrl: String?
    public var width: Int?
    public var height: Int?
    public var accountId: String?

    public init(kind: String, url: String, filename: String? = nil, sizeBytes: Int64? = nil, mimeType: String? = nil, thumbnailUrl: String? = nil, width: Int? = nil, height: Int? = nil, accountId: String? = nil) {
        self.kind = kind
        self.url = url
        self.filename = filename
        self.sizeBytes = sizeBytes
        self.mimeType = mimeType
        self.thumbnailUrl = thumbnailUrl
        self.width = width
        self.height = height
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case url
        case filename
        case sizeBytes
        case mimeType
        case thumbnailUrl
        case width
        case height
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(filename, forKey: .filename)
        try container.encodeIfPresent(sizeBytes, forKey: .sizeBytes)
        try container.encodeIfPresent(mimeType, forKey: .mimeType)
        try container.encodeIfPresent(thumbnailUrl, forKey: .thumbnailUrl)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

