//
// DMMarkReadRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DMMarkReadRequest: Codable, JSONEncodable, Hashable {

    public var messageId: String
    public var accountId: String?

    public init(messageId: String, accountId: String? = nil) {
        self.messageId = messageId
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageId
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messageId, forKey: .messageId)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

