//
// DMMessageEnvelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Generic single-message wrapper used by reply/forward/attach responses. &#x60;message&#x60; is the resulting &#x60;ChatMessage&#x60;.  */
public struct DMMessageEnvelope: Codable, JSONEncodable, Hashable {

    public var message: ChatMessage

    public init(message: ChatMessage) {
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
    }
}

