//
// DMReactionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DMReactionRequest: Codable, JSONEncodable, Hashable {

    public var emoji: String
    public var accountId: String?

    public init(emoji: String, accountId: String? = nil) {
        self.emoji = emoji
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emoji
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emoji, forKey: .emoji)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

