//
// DMReactionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** &#x60;reactions&#x60; shape is provider-specific; treat as opaque. */
public struct DMReactionResponse: Codable, JSONEncodable, Hashable {

    /** Updated reaction list for the message. */
    public var reactions: AnyCodable?

    public init(reactions: AnyCodable? = nil) {
        self.reactions = reactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reactions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reactions, forKey: .reactions)
    }
}

