//
// DMSearchResults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DMSearchResults: Codable, JSONEncodable, Hashable {

    /** Provider-shaped search results. Treat as opaque. */
    public var results: AnyCodable?

    public init(results: AnyCodable? = nil) {
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

