//
// DMThreadReplyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DMThreadReplyRequest: Codable, JSONEncodable, Hashable {

    public var content: String
    public var accountId: String?

    public init(content: String, accountId: String? = nil) {
        self.content = content
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(content, forKey: .content)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

