//
// ExecuteActionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Generic action-execute payload. Tool-specific shape lives in &#x60;params&#x60;. */
public struct ExecuteActionRequest: Codable, JSONEncodable, Hashable {

    public var actionId: String
    public var params: [String: AnyCodable]?
    public var accountId: String?

    public init(actionId: String, params: [String: AnyCodable]? = nil, accountId: String? = nil) {
        self.actionId = actionId
        self.params = params
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actionId
        case params
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(actionId, forKey: .actionId)
        try container.encodeIfPresent(params, forKey: .params)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

