//
// ExportPDFRequestRasterizedSlidesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExportPDFRequestRasterizedSlidesInner: Codable, JSONEncodable, Hashable {

    public var slideId: String
    /** Base64-encoded PNG. */
    public var png: String

    public init(slideId: String, png: String) {
        self.slideId = slideId
        self.png = png
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slideId
        case png
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slideId, forKey: .slideId)
        try container.encode(png, forKey: .png)
    }
}

