//
// FederatedSearch200ResponseItemsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FederatedSearch200ResponseItemsInner: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var entityType: String?
    public var platform: String?
    public var providerId: String?
    public var title: String?
    public var description: String?
    public var snippet: String?
    public var author: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var score: Double?

    public init(id: String? = nil, entityType: String? = nil, platform: String? = nil, providerId: String? = nil, title: String? = nil, description: String? = nil, snippet: String? = nil, author: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, score: Double? = nil) {
        self.id = id
        self.entityType = entityType
        self.platform = platform
        self.providerId = providerId
        self.title = title
        self.description = description
        self.snippet = snippet
        self.author = author
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.score = score
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case entityType = "entity_type"
        case platform
        case providerId = "provider_id"
        case title
        case description
        case snippet
        case author
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case score
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(entityType, forKey: .entityType)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(providerId, forKey: .providerId)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(snippet, forKey: .snippet)
        try container.encodeIfPresent(author, forKey: .author)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(score, forKey: .score)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension FederatedSearch200ResponseItemsInner: Identifiable {}
