//
// Folder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Folder: Codable, JSONEncodable, Hashable {

    public var id: String
    public var provider: String?
    public var accountId: String?
    public var name: String
    public var parentId: String?
    /** Display path from the root (e.g. `/Finance/Q3`). */
    public var path: String
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: String, provider: String? = nil, accountId: String? = nil, name: String, parentId: String? = nil, path: String, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.provider = provider
        self.accountId = accountId
        self.name = name
        self.parentId = parentId
        self.path = path
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case provider
        case accountId
        case name
        case parentId
        case path
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(path, forKey: .path)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Folder: Identifiable {}
