//
// GetEmailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetEmailResponse: Codable, JSONEncodable, Hashable {

    public var email: Email
    public var provider: String

    public init(email: Email, provider: String) {
        self.email = email
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(provider, forKey: .provider)
    }
}

