//
// InboxListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InboxListResponse: Codable, JSONEncodable, Hashable {

    public var items: [InboxItem]
    public var totalCount: Int
    public var hasMore: Bool

    public init(items: [InboxItem], totalCount: Int, hasMore: Bool) {
        self.items = items
        self.totalCount = totalCount
        self.hasMore = hasMore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case totalCount
        case hasMore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(hasMore, forKey: .hasMore)
    }
}

