//
// ListDraftsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListDraftsResponse: Codable, JSONEncodable, Hashable {

    public var drafts: [Draft]
    public var total: Int
    public var nextPageToken: String?
    public var provider: String

    public init(drafts: [Draft], total: Int, nextPageToken: String? = nil, provider: String) {
        self.drafts = drafts
        self.total = total
        self.nextPageToken = nextPageToken
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case drafts
        case total
        case nextPageToken
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(drafts, forKey: .drafts)
        try container.encode(total, forKey: .total)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
        try container.encode(provider, forKey: .provider)
    }
}

