//
// ListChatUsersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListChatUsersResponse: Codable, JSONEncodable, Hashable {

    public var users: [ChatUser]?
    public var total: Int
    public var nextCursor: String?
    public var provider: String

    public init(users: [ChatUser]? = nil, total: Int, nextCursor: String? = nil, provider: String) {
        self.users = users
        self.total = total
        self.nextCursor = nextCursor
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case total
        case nextCursor
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encode(total, forKey: .total)
        try container.encodeIfPresent(nextCursor, forKey: .nextCursor)
        try container.encode(provider, forKey: .provider)
    }
}

