//
// ListEventsData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Shape of &#x60;data&#x60; when returned by &#x60;listEvents&#x60;. Wrapped inside a CalendarOperationResult — clients should access this as &#x60;result.data&#x60; after checking &#x60;result.success&#x60;.  */
public struct ListEventsData: Codable, JSONEncodable, Hashable {

    /** `null` when there are no results (Go nil-slice serialization).  */
    public var events: [SpatioEvent]?
    public var nextPageToken: String?
    public var totalResults: Int?
    public var updatedAt: Date

    public init(events: [SpatioEvent]? = nil, nextPageToken: String? = nil, totalResults: Int? = nil, updatedAt: Date) {
        self.events = events
        self.nextPageToken = nextPageToken
        self.totalResults = totalResults
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
        case nextPageToken = "next_page_token"
        case totalResults = "total_results"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
        try container.encodeIfPresent(totalResults, forKey: .totalResults)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

