//
// ListChannelsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListChannelsResponse: Codable, JSONEncodable, Hashable {

    /** `null` when no results (Go nil-slice serialization). */
    public var channels: [Channel]?
    public var total: Int
    public var nextCursor: String?
    public var provider: String

    public init(channels: [Channel]? = nil, total: Int, nextCursor: String? = nil, provider: String) {
        self.channels = channels
        self.total = total
        self.nextCursor = nextCursor
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channels
        case total
        case nextCursor
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(channels, forKey: .channels)
        try container.encode(total, forKey: .total)
        try container.encodeIfPresent(nextCursor, forKey: .nextCursor)
        try container.encode(provider, forKey: .provider)
    }
}

