//
// MeetingRoom.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MeetingRoom: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String?
    public var workspaceId: String?
    public var createdAt: Date?

    public init(id: String, name: String? = nil, workspaceId: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.name = name
        self.workspaceId = workspaceId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case workspaceId
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension MeetingRoom: Identifiable {}
