//
// OrganizationMemberListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrganizationMemberListResponse: Codable, JSONEncodable, Hashable {

    public var members: [OrganizationMember]
    public var total: Int

    public init(members: [OrganizationMember], total: Int) {
        self.members = members
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case members
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(members, forKey: .members)
        try container.encode(total, forKey: .total)
    }
}

