//
// PasswordRequiredError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returned by &#x60;GET /public/notes/{token}&#x60; when the note is password-protected. &#x60;requiresPassword&#x60; is always &#x60;true&#x60; in this response; &#x60;invalidPassword&#x60; is &#x60;true&#x60; only when a password was supplied and rejected.  */
public struct PasswordRequiredError: Codable, JSONEncodable, Hashable {

    /** Human-readable error message. */
    public var error: String
    /** Machine-readable error code. Stable across releases for the canonical codes (`ambiguous_account`, `no_notes_provider`, `note_not_found`). Absent for generic errors.  */
    public var code: String?
    public var requiresPassword: Bool
    public var invalidPassword: Bool?

    public init(error: String, code: String? = nil, requiresPassword: Bool, invalidPassword: Bool? = nil) {
        self.error = error
        self.code = code
        self.requiresPassword = requiresPassword
        self.invalidPassword = invalidPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case code
        case requiresPassword
        case invalidPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encode(requiresPassword, forKey: .requiresPassword)
        try container.encodeIfPresent(invalidPassword, forKey: .invalidPassword)
    }
}

