//
// PATListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PATListResponse: Codable, JSONEncodable, Hashable {

    public var tokens: [PersonalAccessToken]
    public var availableScopes: [String]?

    public init(tokens: [PersonalAccessToken], availableScopes: [String]? = nil) {
        self.tokens = tokens
        self.availableScopes = availableScopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokens
        case availableScopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokens, forKey: .tokens)
        try container.encodeIfPresent(availableScopes, forKey: .availableScopes)
    }
}

