//
// PATScopesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PATScopesResponse: Codable, JSONEncodable, Hashable {

    public var scopes: [String]

    public init(scopes: [String]) {
        self.scopes = scopes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case scopes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(scopes, forKey: .scopes)
    }
}

