//
// PresentationListEnvelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PresentationListEnvelope: Codable, JSONEncodable, Hashable {

    public var items: [Presentation]
    public var accounts: [AccountStatus]

    public init(items: [Presentation], accounts: [AccountStatus]) {
        self.items = items
        self.accounts = accounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case accounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(accounts, forKey: .accounts)
    }
}

