//
// Record.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Record: Codable, JSONEncodable, Hashable {

    public var id: String
    public var organizationId: String?
    public var recordTypeId: String?
    public var name: String?
    public var attributes: [String: AnyCodable]?
    public var metadata: [String: AnyCodable]?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String, organizationId: String? = nil, recordTypeId: String? = nil, name: String? = nil, attributes: [String: AnyCodable]? = nil, metadata: [String: AnyCodable]? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.organizationId = organizationId
        self.recordTypeId = recordTypeId
        self.name = name
        self.attributes = attributes
        self.metadata = metadata
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case organizationId = "organization_id"
        case recordTypeId = "record_type_id"
        case name
        case attributes
        case metadata
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(organizationId, forKey: .organizationId)
        try container.encodeIfPresent(recordTypeId, forKey: .recordTypeId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Record: Identifiable {}
