//
// RefreshConnectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RefreshConnectionRequest: Codable, JSONEncodable, Hashable {

    public var connectionId: String
    public var accountId: String?

    public init(connectionId: String, accountId: String? = nil) {
        self.connectionId = connectionId
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connectionId
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(connectionId, forKey: .connectionId)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

