//
// Reminder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Reminder: Codable, JSONEncodable, Hashable {

    public var method: ReminderMethod
    /** Trigger time in minutes before the event start. */
    public var minutes: Int

    public init(method: ReminderMethod, minutes: Int) {
        self.method = method
        self.minutes = minutes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case method
        case minutes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(method, forKey: .method)
        try container.encode(minutes, forKey: .minutes)
    }
}

