//
// RevokeOtherSessionsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RevokeOtherSessionsResponse: Codable, JSONEncodable, Hashable {

    /** Count of sessions revoked. */
    public var revoked: Int?

    public init(revoked: Int? = nil) {
        self.revoked = revoked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case revoked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(revoked, forKey: .revoked)
    }
}

