//
// RoutineRunCompleteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoutineRunCompleteRequest: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var metadata: [String: AnyCodable]?

    public init(status: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.status = status
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

