//
// Routine.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Routine: Codable, JSONEncodable, Hashable {

    public var id: String
    public var workspaceId: String?
    public var name: String?
    public var description: String?
    public var schedule: [String: AnyCodable]?
    public var status: String?
    public var metadata: [String: AnyCodable]?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: String, workspaceId: String? = nil, name: String? = nil, description: String? = nil, schedule: [String: AnyCodable]? = nil, status: String? = nil, metadata: [String: AnyCodable]? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.workspaceId = workspaceId
        self.name = name
        self.description = description
        self.schedule = schedule
        self.status = status
        self.metadata = metadata
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case workspaceId
        case name
        case description
        case schedule
        case status
        case metadata
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(workspaceId, forKey: .workspaceId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(schedule, forKey: .schedule)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Routine: Identifiable {}
