//
// SearchEmailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchEmailsResponse: Codable, JSONEncodable, Hashable {

    /** `null` when there are no results (Go nil-slice serialization). Treat as equivalent to an empty array.  */
    public var emails: [Email]?
    public var total: Int
    public var nextPageToken: String?
    public var provider: String

    public init(emails: [Email]? = nil, total: Int, nextPageToken: String? = nil, provider: String) {
        self.emails = emails
        self.total = total
        self.nextPageToken = nextPageToken
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emails
        case total
        case nextPageToken
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(emails, forKey: .emails)
        try container.encode(total, forKey: .total)
        try container.encodeIfPresent(nextPageToken, forKey: .nextPageToken)
        try container.encode(provider, forKey: .provider)
    }
}

