//
// SendChatMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendChatMessageRequest: Codable, JSONEncodable, Hashable {

    public var accountId: String?
    /** Channel or DM id (provider-scoped). */
    public var channel: String
    public var text: String
    public var threadId: String?
    /** Provider-specific rich-message blocks. */
    public var blocks: [[String: AnyCodable]]?

    public init(accountId: String? = nil, channel: String, text: String, threadId: String? = nil, blocks: [[String: AnyCodable]]? = nil) {
        self.accountId = accountId
        self.channel = channel
        self.text = text
        self.threadId = threadId
        self.blocks = blocks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case channel
        case text
        case threadId
        case blocks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(channel, forKey: .channel)
        try container.encode(text, forKey: .text)
        try container.encodeIfPresent(threadId, forKey: .threadId)
        try container.encodeIfPresent(blocks, forKey: .blocks)
    }
}

