//
// SendEmailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendEmailResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool
    public var messageId: String
    public var threadId: String?
    public var provider: String
    public var error: String?

    public init(success: Bool, messageId: String, threadId: String? = nil, provider: String, error: String? = nil) {
        self.success = success
        self.messageId = messageId
        self.threadId = threadId
        self.provider = provider
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case messageId
        case threadId
        case provider
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(messageId, forKey: .messageId)
        try container.encodeIfPresent(threadId, forKey: .threadId)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

