//
// ShareSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Public share configuration for a note. Owner-only mutation; unauthenticated readers consume &#x60;GET /public/notes/{token}&#x60; instead.  */
public struct ShareSettings: Codable, JSONEncodable, Hashable {

    public var isPublic: Bool
    public var hasPassword: Bool
    /** Opaque token embedded in the public URL. Empty when `isPublic` is false.  */
    public var shareToken: String?
    /** Fully-qualified public viewer URL. Computed server-side from `PUBLIC_VIEWER_BASE` (defaults to `https://spatio.app`) and the share token. Empty when the note is private.  */
    public var shareUrl: String?
    /** When the current password was set, if any. */
    public var passwordSetAt: Date?

    public init(isPublic: Bool, hasPassword: Bool, shareToken: String? = nil, shareUrl: String? = nil, passwordSetAt: Date? = nil) {
        self.isPublic = isPublic
        self.hasPassword = hasPassword
        self.shareToken = shareToken
        self.shareUrl = shareUrl
        self.passwordSetAt = passwordSetAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isPublic
        case hasPassword
        case shareToken
        case shareUrl
        case passwordSetAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isPublic, forKey: .isPublic)
        try container.encode(hasPassword, forKey: .hasPassword)
        try container.encodeIfPresent(shareToken, forKey: .shareToken)
        try container.encodeIfPresent(shareUrl, forKey: .shareUrl)
        try container.encodeIfPresent(passwordSetAt, forKey: .passwordSetAt)
    }
}

