//
// SignInMethods.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignInMethods: Codable, JSONEncodable, Hashable {

    public var email: String
    public var hasPassword: Bool
    public var providers: [SignInMethodsProvidersInner]?

    public init(email: String, hasPassword: Bool, providers: [SignInMethodsProvidersInner]? = nil) {
        self.email = email
        self.hasPassword = hasPassword
        self.providers = providers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case hasPassword
        case providers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(hasPassword, forKey: .hasPassword)
        try container.encodeIfPresent(providers, forKey: .providers)
    }
}

