//
// SlideList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SlideList: Codable, JSONEncodable, Hashable {

    public var slides: [Slide]
    public var total: Int

    public init(slides: [Slide], total: Int) {
        self.slides = slides
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slides
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slides, forKey: .slides)
        try container.encode(total, forKey: .total)
    }
}

