//
// SpatioFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A user file. Files belong to one connected file provider account (&#x60;accountId&#x60; + &#x60;provider&#x60;); native storage uses Spatio&#39;s block-store, external providers (Google Drive, Dropbox, etc.) round-trip through Spatio.  Schema name is &#x60;SpatioFile&#x60; (not &#x60;File&#x60;) to avoid the &#x60;java.io.File&#x60; collision that breaks the Kotlin SDK generator when the schema is named &#x60;File&#x60;.  */
public struct SpatioFile: Codable, JSONEncodable, Hashable {

    public var id: String
    public var provider: String?
    public var accountId: String?
    public var name: String
    /** Bytes. */
    public var size: Int64
    public var mimeType: String
    public var folderId: String?
    /** Backing storage class — `r2`, `gdrive`, `dropbox`, etc. Provider-specific; treat as opaque.  */
    public var storageType: String
    /** Pre-signed download URL when one is cached on the row. Use `GET /v1/files/{id}/download` for a guaranteed-fresh URL — this field can lag past expiry.  */
    public var downloadUrl: String?
    public var metadata: [String: AnyCodable]?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: String, provider: String? = nil, accountId: String? = nil, name: String, size: Int64, mimeType: String, folderId: String? = nil, storageType: String, downloadUrl: String? = nil, metadata: [String: AnyCodable]? = nil, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.provider = provider
        self.accountId = accountId
        self.name = name
        self.size = size
        self.mimeType = mimeType
        self.folderId = folderId
        self.storageType = storageType
        self.downloadUrl = downloadUrl
        self.metadata = metadata
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case provider
        case accountId
        case name
        case size
        case mimeType
        case folderId
        case storageType
        case downloadUrl
        case metadata
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(name, forKey: .name)
        try container.encode(size, forKey: .size)
        try container.encode(mimeType, forKey: .mimeType)
        try container.encodeIfPresent(folderId, forKey: .folderId)
        try container.encode(storageType, forKey: .storageType)
        try container.encodeIfPresent(downloadUrl, forKey: .downloadUrl)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SpatioFile: Identifiable {}
