//
// SuccessFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Lightweight ack returned by mutations that have no other body (&#x60;DELETE /v1/notes/:id&#x60;, block move, etc.).  */
public struct SuccessFlag: Codable, JSONEncodable, Hashable {

    public var success: Bool

    public init(success: Bool) {
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
    }
}

