//
// TaskCommentMutationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaskCommentMutationResponse: Codable, JSONEncodable, Hashable {

    public var comment: TaskComment
    public var success: Bool

    public init(comment: TaskComment, success: Bool) {
        self.comment = comment
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comment, forKey: .comment)
        try container.encode(success, forKey: .success)
    }
}

