//
// UpdateContactCategoryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateContactCategoryRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var color: String?
    public var description: String?

    public init(name: String? = nil, color: String? = nil, description: String? = nil) {
        self.name = name
        self.color = color
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case color
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

