//
// UpdateSheetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Partial update — every field is optional. */
public struct UpdateSheetRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var data: [String: AnyCodable]?
    public var rowCount: Int?
    public var columnCount: Int?
    public var isPublic: Bool?
    public var isReadOnly: Bool?

    public init(name: String? = nil, description: String? = nil, data: [String: AnyCodable]? = nil, rowCount: Int? = nil, columnCount: Int? = nil, isPublic: Bool? = nil, isReadOnly: Bool? = nil) {
        self.name = name
        self.description = description
        self.data = data
        self.rowCount = rowCount
        self.columnCount = columnCount
        self.isPublic = isPublic
        self.isReadOnly = isReadOnly
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case data
        case rowCount
        case columnCount
        case isPublic
        case isReadOnly
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(rowCount, forKey: .rowCount)
        try container.encodeIfPresent(columnCount, forKey: .columnCount)
        try container.encodeIfPresent(isPublic, forKey: .isPublic)
        try container.encodeIfPresent(isReadOnly, forKey: .isReadOnly)
    }
}

