//
// UpdateEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Sparse update. &#x60;updates&#x60; is a free-form map of fields to change; only keys present are applied. The server-side capability gate rejects fields that the underlying provider doesn&#39;t support.  */
public struct UpdateEventRequest: Codable, JSONEncodable, Hashable {

    public enum SendUpdates: String, Codable, CaseIterable {
        case all = "all"
        case externalonly = "externalOnly"
        case _none = "none"
    }
    public var accountId: String
    public var updates: [String: AnyCodable]
    public var sendUpdates: SendUpdates?

    public init(accountId: String, updates: [String: AnyCodable], sendUpdates: SendUpdates? = nil) {
        self.accountId = accountId
        self.updates = updates
        self.sendUpdates = sendUpdates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId = "account_id"
        case updates
        case sendUpdates = "send_updates"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(updates, forKey: .updates)
        try container.encodeIfPresent(sendUpdates, forKey: .sendUpdates)
    }
}

