//
// UpdateAgentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateAgentRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var systemPrompt: String?
    public var tools: [String]?
    public var icon: String?
    public var color: String?
    public var metadata: [String: AnyCodable]?

    public init(name: String? = nil, description: String? = nil, systemPrompt: String? = nil, tools: [String]? = nil, icon: String? = nil, color: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.name = name
        self.description = description
        self.systemPrompt = systemPrompt
        self.tools = tools
        self.icon = icon
        self.color = color
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case systemPrompt
        case tools
        case icon
        case color
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(systemPrompt, forKey: .systemPrompt)
        try container.encodeIfPresent(tools, forKey: .tools)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

