//
// UpdateContactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateContactRequest: Codable, JSONEncodable, Hashable {

    public var firstName: String?
    public var lastName: String?
    public var email: String?
    public var phone: String?
    public var company: String?
    public var title: String?
    public var notes: String?
    public var metadata: [String: AnyCodable]?

    public init(firstName: String? = nil, lastName: String? = nil, email: String? = nil, phone: String? = nil, company: String? = nil, title: String? = nil, notes: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.phone = phone
        self.company = company
        self.title = title
        self.notes = notes
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case phone
        case company
        case title
        case notes
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(company, forKey: .company)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

