//
// UpdateSlideElementRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Partial update — every field optional. */
public struct UpdateSlideElementRequest: Codable, JSONEncodable, Hashable {

    public var elementType: String?
    public var content: [String: AnyCodable]?
    public var x: Double?
    public var y: Double?
    public var width: Double?
    public var height: Double?
    public var rotation: Double?
    public var zIndex: Int?

    public init(elementType: String? = nil, content: [String: AnyCodable]? = nil, x: Double? = nil, y: Double? = nil, width: Double? = nil, height: Double? = nil, rotation: Double? = nil, zIndex: Int? = nil) {
        self.elementType = elementType
        self.content = content
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.rotation = rotation
        self.zIndex = zIndex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case elementType
        case content
        case x
        case y
        case width
        case height
        case rotation
        case zIndex
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(elementType, forKey: .elementType)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(x, forKey: .x)
        try container.encodeIfPresent(y, forKey: .y)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(rotation, forKey: .rotation)
        try container.encodeIfPresent(zIndex, forKey: .zIndex)
    }
}

