//
// UpdateRoutineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateRoutineRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var schedule: [String: AnyCodable]?
    public var status: String?
    public var metadata: [String: AnyCodable]?

    public init(name: String? = nil, description: String? = nil, schedule: [String: AnyCodable]? = nil, status: String? = nil, metadata: [String: AnyCodable]? = nil) {
        self.name = name
        self.description = description
        self.schedule = schedule
        self.status = status
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case schedule
        case status
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(schedule, forKey: .schedule)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

