//
// UpdateRowRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateRowRequest: Codable, JSONEncodable, Hashable {

    /** Sparse update. Keys present in the map overwrite that column; keys absent are preserved.  */
    public var cells: [String: AnyCodable]

    public init(cells: [String: AnyCodable]) {
        self.cells = cells
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cells
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cells, forKey: .cells)
    }
}

