//
// ActionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ActionsAPI {

    /**
     Renderer-side execute alias. The canonical endpoint is `POST /v1/agent/actions/execute`; this path delegates to the same handler. 
     
     - parameter executeActionRequest: (body)  
     - returns: ExecuteActionResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func executeAction(executeActionRequest: ExecuteActionRequest) async throws -> ExecuteActionResponse {
        return try await executeActionWithRequestBuilder(executeActionRequest: executeActionRequest).execute().body
    }

    /**
     Renderer-side execute alias. The canonical endpoint is `POST /v1/agent/actions/execute`; this path delegates to the same handler. 
     - POST /v1/actions/execute
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter executeActionRequest: (body)  
     - returns: RequestBuilder<ExecuteActionResponse> 
     */
    open class func executeActionWithRequestBuilder(executeActionRequest: ExecuteActionRequest) -> RequestBuilder<ExecuteActionResponse> {
        let localVariablePath = "/v1/actions/execute"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: executeActionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ExecuteActionResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch a single core action by id.
     
     - parameter id: (path)  
     - returns: CoreAction
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCoreAction(id: String) async throws -> CoreAction {
        return try await getCoreActionWithRequestBuilder(id: id).execute().body
    }

    /**
     Fetch a single core action by id.
     - GET /v1/actions/core/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<CoreAction> 
     */
    open class func getCoreActionWithRequestBuilder(id: String) -> RequestBuilder<CoreAction> {
        var localVariablePath = "/v1/actions/core/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CoreAction>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List every action the agent platform exposes.
     
     - returns: [ActionDescriptor]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listAvailableActions() async throws -> [ActionDescriptor] {
        return try await listAvailableActionsWithRequestBuilder().execute().body
    }

    /**
     List every action the agent platform exposes.
     - GET /v1/actions/available
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<[ActionDescriptor]> 
     */
    open class func listAvailableActionsWithRequestBuilder() -> RequestBuilder<[ActionDescriptor]> {
        let localVariablePath = "/v1/actions/available"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ActionDescriptor]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List renderer-curated \"core actions\" (command-palette + keybindings backing).
     
     - returns: CoreActionListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listCoreActions() async throws -> CoreActionListResponse {
        return try await listCoreActionsWithRequestBuilder().execute().body
    }

    /**
     List renderer-curated \"core actions\" (command-palette + keybindings backing).
     - GET /v1/actions/core
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<CoreActionListResponse> 
     */
    open class func listCoreActionsWithRequestBuilder() -> RequestBuilder<CoreActionListResponse> {
        let localVariablePath = "/v1/actions/core"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CoreActionListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Core actions filtered to one platform.
     
     - parameter platform: (path)  
     - returns: CoreActionListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listCoreActionsByPlatform(platform: String) async throws -> CoreActionListResponse {
        return try await listCoreActionsByPlatformWithRequestBuilder(platform: platform).execute().body
    }

    /**
     Core actions filtered to one platform.
     - GET /v1/actions/core/platform/{platform}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter platform: (path)  
     - returns: RequestBuilder<CoreActionListResponse> 
     */
    open class func listCoreActionsByPlatformWithRequestBuilder(platform: String) -> RequestBuilder<CoreActionListResponse> {
        var localVariablePath = "/v1/actions/core/platform/{platform}"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CoreActionListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List actions tagged for a specific platform (notes, mail, ...).
     
     - parameter platform: (path)  
     - returns: [ActionDescriptor]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listPlatformActions(platform: String) async throws -> [ActionDescriptor] {
        return try await listPlatformActionsWithRequestBuilder(platform: platform).execute().body
    }

    /**
     List actions tagged for a specific platform (notes, mail, ...).
     - GET /v1/actions/platform/{platform}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter platform: (path)  
     - returns: RequestBuilder<[ActionDescriptor]> 
     */
    open class func listPlatformActionsWithRequestBuilder(platform: String) -> RequestBuilder<[ActionDescriptor]> {
        var localVariablePath = "/v1/actions/platform/{platform}"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ActionDescriptor]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
