//
// CallsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CallsAPI {

    /**
     Start a new call.
     
     - parameter createCallRequest: (body)  (optional)
     - returns: SpatioCall
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createCall(createCallRequest: CreateCallRequest? = nil) async throws -> SpatioCall {
        return try await createCallWithRequestBuilder(createCallRequest: createCallRequest).execute().body
    }

    /**
     Start a new call.
     - POST /v1/calls
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createCallRequest: (body)  (optional)
     - returns: RequestBuilder<SpatioCall> 
     */
    open class func createCallWithRequestBuilder(createCallRequest: CreateCallRequest? = nil) -> RequestBuilder<SpatioCall> {
        let localVariablePath = "/v1/calls"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createCallRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpatioCall>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a persistent meeting room.
     
     - parameter createMeetingRoomRequest: (body)  
     - returns: MeetingRoom
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createMeetingRoom(createMeetingRoomRequest: CreateMeetingRoomRequest) async throws -> MeetingRoom {
        return try await createMeetingRoomWithRequestBuilder(createMeetingRoomRequest: createMeetingRoomRequest).execute().body
    }

    /**
     Create a persistent meeting room.
     - POST /v1/calls/rooms
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createMeetingRoomRequest: (body)  
     - returns: RequestBuilder<MeetingRoom> 
     */
    open class func createMeetingRoomWithRequestBuilder(createMeetingRoomRequest: CreateMeetingRoomRequest) -> RequestBuilder<MeetingRoom> {
        let localVariablePath = "/v1/calls/rooms"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createMeetingRoomRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MeetingRoom>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a recording.
     
     - parameter recordingId: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteCallRecording(recordingId: String) async throws {
        return try await deleteCallRecordingWithRequestBuilder(recordingId: recordingId).execute().body
    }

    /**
     Delete a recording.
     - DELETE /v1/calls/recordings/{recordingId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter recordingId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCallRecordingWithRequestBuilder(recordingId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/calls/recordings/{recordingId}"
        let recordingIdPreEscape = "\(APIHelper.mapValueToPathItem(recordingId))"
        let recordingIdPostEscape = recordingIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{recordingId}", with: recordingIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     End a call (host only).
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func endCall(id: String) async throws {
        return try await endCallWithRequestBuilder(id: id).execute().body
    }

    /**
     End a call (host only).
     - POST /v1/calls/{id}/end
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func endCallWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/calls/{id}/end"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Time-series bandwidth metrics.
     
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getBandwidthHistory() async throws -> [String: AnyCodable] {
        return try await getBandwidthHistoryWithRequestBuilder().execute().body
    }

    /**
     Time-series bandwidth metrics.
     - GET /v1/calls/bandwidth/history
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getBandwidthHistoryWithRequestBuilder() -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/v1/calls/bandwidth/history"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Aggregate bandwidth metrics.
     
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getBandwidthSummary() async throws -> [String: AnyCodable] {
        return try await getBandwidthSummaryWithRequestBuilder().execute().body
    }

    /**
     Aggregate bandwidth metrics.
     - GET /v1/calls/bandwidth/summary
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getBandwidthSummaryWithRequestBuilder() -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/v1/calls/bandwidth/summary"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch a call.
     
     - parameter id: (path)  
     - returns: SpatioCall
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getCall(id: String) async throws -> SpatioCall {
        return try await getCallWithRequestBuilder(id: id).execute().body
    }

    /**
     Fetch a call.
     - GET /v1/calls/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<SpatioCall> 
     */
    open class func getCallWithRequestBuilder(id: String) -> RequestBuilder<SpatioCall> {
        var localVariablePath = "/v1/calls/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SpatioCall>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch a meeting room.
     
     - parameter id: (path)  
     - returns: MeetingRoom
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMeetingRoom(id: String) async throws -> MeetingRoom {
        return try await getMeetingRoomWithRequestBuilder(id: id).execute().body
    }

    /**
     Fetch a meeting room.
     - GET /v1/calls/rooms/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<MeetingRoom> 
     */
    open class func getMeetingRoomWithRequestBuilder(id: String) -> RequestBuilder<MeetingRoom> {
        var localVariablePath = "/v1/calls/rooms/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MeetingRoom>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Join a call.
     
     - parameter id: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func joinCall(id: String) async throws -> [String: AnyCodable] {
        return try await joinCallWithRequestBuilder(id: id).execute().body
    }

    /**
     Join a call.
     - POST /v1/calls/{id}/join
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func joinCallWithRequestBuilder(id: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/calls/{id}/join"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Leave a call.
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func leaveCall(id: String) async throws {
        return try await leaveCallWithRequestBuilder(id: id).execute().body
    }

    /**
     Leave a call.
     - POST /v1/calls/{id}/leave
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func leaveCallWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/calls/{id}/leave"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List active calls.
     
     - returns: CallListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listActiveCalls() async throws -> CallListResponse {
        return try await listActiveCallsWithRequestBuilder().execute().body
    }

    /**
     List active calls.
     - GET /v1/calls
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<CallListResponse> 
     */
    open class func listActiveCallsWithRequestBuilder() -> RequestBuilder<CallListResponse> {
        let localVariablePath = "/v1/calls"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CallListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List recordings for a call.
     
     - parameter id: (path)  
     - returns: CallRecordingListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listCallRecordings(id: String) async throws -> CallRecordingListResponse {
        return try await listCallRecordingsWithRequestBuilder(id: id).execute().body
    }

    /**
     List recordings for a call.
     - GET /v1/calls/{id}/recordings
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<CallRecordingListResponse> 
     */
    open class func listCallRecordingsWithRequestBuilder(id: String) -> RequestBuilder<CallRecordingListResponse> {
        var localVariablePath = "/v1/calls/{id}/recordings"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CallRecordingListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Start a recording (host only).
     
     - parameter id: (path)  
     - returns: CallRecording
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func startCallRecording(id: String) async throws -> CallRecording {
        return try await startCallRecordingWithRequestBuilder(id: id).execute().body
    }

    /**
     Start a recording (host only).
     - POST /v1/calls/{id}/recordings/start
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<CallRecording> 
     */
    open class func startCallRecordingWithRequestBuilder(id: String) -> RequestBuilder<CallRecording> {
        var localVariablePath = "/v1/calls/{id}/recordings/start"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CallRecording>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Stop an in-progress recording.
     
     - parameter id: (path)  
     - parameter recordingId: (path)  
     - returns: CallRecording
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func stopCallRecording(id: String, recordingId: String) async throws -> CallRecording {
        return try await stopCallRecordingWithRequestBuilder(id: id, recordingId: recordingId).execute().body
    }

    /**
     Stop an in-progress recording.
     - POST /v1/calls/{id}/recordings/{recordingId}/stop
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter recordingId: (path)  
     - returns: RequestBuilder<CallRecording> 
     */
    open class func stopCallRecordingWithRequestBuilder(id: String, recordingId: String) -> RequestBuilder<CallRecording> {
        var localVariablePath = "/v1/calls/{id}/recordings/{recordingId}/stop"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let recordingIdPreEscape = "\(APIHelper.mapValueToPathItem(recordingId))"
        let recordingIdPostEscape = recordingIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{recordingId}", with: recordingIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CallRecording>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Toggle participant audio/video/screen-share state.
     
     - parameter id: (path)  
     - parameter updateParticipantStateRequest: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateCallParticipantState(id: String, updateParticipantStateRequest: UpdateParticipantStateRequest) async throws -> [String: AnyCodable] {
        return try await updateCallParticipantStateWithRequestBuilder(id: id, updateParticipantStateRequest: updateParticipantStateRequest).execute().body
    }

    /**
     Toggle participant audio/video/screen-share state.
     - PATCH /v1/calls/{id}/participant
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateParticipantStateRequest: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func updateCallParticipantStateWithRequestBuilder(id: String, updateParticipantStateRequest: UpdateParticipantStateRequest) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/calls/{id}/participant"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateParticipantStateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter requestBody: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceCreateCall(org: String, workspace: String, requestBody: [String: AnyCodable]) async throws -> [String: AnyCodable] {
        return try await workspaceCreateCallWithRequestBuilder(org: org, workspace: workspace, requestBody: requestBody).execute().body
    }

    /**
     - POST /v1/organizations/{org}/workspaces/{workspace}/calls
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter requestBody: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceCreateCallWithRequestBuilder(org: String, workspace: String, requestBody: [String: AnyCodable]) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter requestBody: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceCreateMeetingRoom(org: String, workspace: String, requestBody: [String: AnyCodable]) async throws -> [String: AnyCodable] {
        return try await workspaceCreateMeetingRoomWithRequestBuilder(org: org, workspace: workspace, requestBody: requestBody).execute().body
    }

    /**
     - POST /v1/organizations/{org}/workspaces/{workspace}/calls/rooms
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter requestBody: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceCreateMeetingRoomWithRequestBuilder(org: String, workspace: String, requestBody: [String: AnyCodable]) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/rooms"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter recordingId: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceDeleteCallRecording(org: String, workspace: String, recordingId: String) async throws {
        return try await workspaceDeleteCallRecordingWithRequestBuilder(org: org, workspace: workspace, recordingId: recordingId).execute().body
    }

    /**
     - DELETE /v1/organizations/{org}/workspaces/{workspace}/calls/recordings/{recordingId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter recordingId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func workspaceDeleteCallRecordingWithRequestBuilder(org: String, workspace: String, recordingId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/recordings/{recordingId}"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let recordingIdPreEscape = "\(APIHelper.mapValueToPathItem(recordingId))"
        let recordingIdPostEscape = recordingIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{recordingId}", with: recordingIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceEndCall(org: String, workspace: String, id: String) async throws {
        return try await workspaceEndCallWithRequestBuilder(org: org, workspace: workspace, id: id).execute().body
    }

    /**
     - POST /v1/organizations/{org}/workspaces/{workspace}/calls/{id}/end
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func workspaceEndCallWithRequestBuilder(org: String, workspace: String, id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/end"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceGetBandwidthHistory(org: String, workspace: String) async throws -> [String: AnyCodable] {
        return try await workspaceGetBandwidthHistoryWithRequestBuilder(org: org, workspace: workspace).execute().body
    }

    /**
     - GET /v1/organizations/{org}/workspaces/{workspace}/calls/bandwidth/history
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceGetBandwidthHistoryWithRequestBuilder(org: String, workspace: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/bandwidth/history"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceGetBandwidthSummary(org: String, workspace: String) async throws -> [String: AnyCodable] {
        return try await workspaceGetBandwidthSummaryWithRequestBuilder(org: org, workspace: workspace).execute().body
    }

    /**
     - GET /v1/organizations/{org}/workspaces/{workspace}/calls/bandwidth/summary
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceGetBandwidthSummaryWithRequestBuilder(org: String, workspace: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/bandwidth/summary"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceGetCall(org: String, workspace: String, id: String) async throws -> [String: AnyCodable] {
        return try await workspaceGetCallWithRequestBuilder(org: org, workspace: workspace, id: id).execute().body
    }

    /**
     - GET /v1/organizations/{org}/workspaces/{workspace}/calls/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceGetCallWithRequestBuilder(org: String, workspace: String, id: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceGetMeetingRoom(org: String, workspace: String, id: String) async throws -> [String: AnyCodable] {
        return try await workspaceGetMeetingRoomWithRequestBuilder(org: org, workspace: workspace, id: id).execute().body
    }

    /**
     - GET /v1/organizations/{org}/workspaces/{workspace}/calls/rooms/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceGetMeetingRoomWithRequestBuilder(org: String, workspace: String, id: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/rooms/{id}"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceJoinCall(org: String, workspace: String, id: String) async throws -> [String: AnyCodable] {
        return try await workspaceJoinCallWithRequestBuilder(org: org, workspace: workspace, id: id).execute().body
    }

    /**
     - POST /v1/organizations/{org}/workspaces/{workspace}/calls/{id}/join
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceJoinCallWithRequestBuilder(org: String, workspace: String, id: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/join"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceLeaveCall(org: String, workspace: String, id: String) async throws {
        return try await workspaceLeaveCallWithRequestBuilder(org: org, workspace: workspace, id: id).execute().body
    }

    /**
     - POST /v1/organizations/{org}/workspaces/{workspace}/calls/{id}/leave
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func workspaceLeaveCallWithRequestBuilder(org: String, workspace: String, id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/leave"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceListActiveCalls(org: String, workspace: String) async throws -> [String: AnyCodable] {
        return try await workspaceListActiveCallsWithRequestBuilder(org: org, workspace: workspace).execute().body
    }

    /**
     - GET /v1/organizations/{org}/workspaces/{workspace}/calls
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceListActiveCallsWithRequestBuilder(org: String, workspace: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceListCallRecordings(org: String, workspace: String, id: String) async throws -> [String: AnyCodable] {
        return try await workspaceListCallRecordingsWithRequestBuilder(org: org, workspace: workspace, id: id).execute().body
    }

    /**
     - GET /v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceListCallRecordingsWithRequestBuilder(org: String, workspace: String, id: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceStartCallRecording(org: String, workspace: String, id: String) async throws -> [String: AnyCodable] {
        return try await workspaceStartCallRecordingWithRequestBuilder(org: org, workspace: workspace, id: id).execute().body
    }

    /**
     - POST /v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings/start
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceStartCallRecordingWithRequestBuilder(org: String, workspace: String, id: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings/start"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - parameter recordingId: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceStopCallRecording(org: String, workspace: String, id: String, recordingId: String) async throws -> [String: AnyCodable] {
        return try await workspaceStopCallRecordingWithRequestBuilder(org: org, workspace: workspace, id: id, recordingId: recordingId).execute().body
    }

    /**
     - POST /v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings/{recordingId}/stop
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - parameter recordingId: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceStopCallRecordingWithRequestBuilder(org: String, workspace: String, id: String, recordingId: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/recordings/{recordingId}/stop"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let recordingIdPreEscape = "\(APIHelper.mapValueToPathItem(recordingId))"
        let recordingIdPostEscape = recordingIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{recordingId}", with: recordingIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - parameter requestBody: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func workspaceUpdateCallParticipant(org: String, workspace: String, id: String, requestBody: [String: AnyCodable]) async throws -> [String: AnyCodable] {
        return try await workspaceUpdateCallParticipantWithRequestBuilder(org: org, workspace: workspace, id: id, requestBody: requestBody).execute().body
    }

    /**
     - PATCH /v1/organizations/{org}/workspaces/{workspace}/calls/{id}/participant
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter org: (path)  
     - parameter workspace: (path)  
     - parameter id: (path)  
     - parameter requestBody: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func workspaceUpdateCallParticipantWithRequestBuilder(org: String, workspace: String, id: String, requestBody: [String: AnyCodable]) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/organizations/{org}/workspaces/{workspace}/calls/{id}/participant"
        let orgPreEscape = "\(APIHelper.mapValueToPathItem(org))"
        let orgPostEscape = orgPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{org}", with: orgPostEscape, options: .literal, range: nil)
        let workspacePreEscape = "\(APIHelper.mapValueToPathItem(workspace))"
        let workspacePostEscape = workspacePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{workspace}", with: workspacePostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
