//
// ContactsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ContactsAPI {

    /**
     Assign a category to a contact.
     
     - parameter id: (path)  
     - parameter assignContactCategoryRequest: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func assignContactCategory(id: String, assignContactCategoryRequest: AssignContactCategoryRequest) async throws {
        return try await assignContactCategoryWithRequestBuilder(id: id, assignContactCategoryRequest: assignContactCategoryRequest).execute().body
    }

    /**
     Assign a category to a contact.
     - POST /v1/contacts/{id}/categories
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter assignContactCategoryRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func assignContactCategoryWithRequestBuilder(id: String, assignContactCategoryRequest: AssignContactCategoryRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/contacts/{id}/categories"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: assignContactCategoryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a contact.
     
     - parameter createContactRequest: (body)  
     - returns: Contact
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createContact(createContactRequest: CreateContactRequest) async throws -> Contact {
        return try await createContactWithRequestBuilder(createContactRequest: createContactRequest).execute().body
    }

    /**
     Create a contact.
     - POST /v1/contacts
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createContactRequest: (body)  
     - returns: RequestBuilder<Contact> 
     */
    open class func createContactWithRequestBuilder(createContactRequest: CreateContactRequest) -> RequestBuilder<Contact> {
        let localVariablePath = "/v1/contacts"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createContactRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Contact>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a contact category.
     
     - parameter createContactCategoryRequest: (body)  
     - returns: ContactCategory
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createContactCategory(createContactCategoryRequest: CreateContactCategoryRequest) async throws -> ContactCategory {
        return try await createContactCategoryWithRequestBuilder(createContactCategoryRequest: createContactCategoryRequest).execute().body
    }

    /**
     Create a contact category.
     - POST /v1/contacts/categories
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createContactCategoryRequest: (body)  
     - returns: RequestBuilder<ContactCategory> 
     */
    open class func createContactCategoryWithRequestBuilder(createContactCategoryRequest: CreateContactCategoryRequest) -> RequestBuilder<ContactCategory> {
        let localVariablePath = "/v1/contacts/categories"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createContactCategoryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ContactCategory>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a contact.
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteContact(id: String) async throws {
        return try await deleteContactWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete a contact.
     - DELETE /v1/contacts/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteContactWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/contacts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a category.
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteContactCategory(id: String) async throws {
        return try await deleteContactCategoryWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete a category.
     - DELETE /v1/contacts/categories/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteContactCategoryWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/contacts/categories/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch a contact.
     
     - parameter id: (path)  
     - returns: Contact
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getContact(id: String) async throws -> Contact {
        return try await getContactWithRequestBuilder(id: id).execute().body
    }

    /**
     Fetch a contact.
     - GET /v1/contacts/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Contact> 
     */
    open class func getContactWithRequestBuilder(id: String) -> RequestBuilder<Contact> {
        var localVariablePath = "/v1/contacts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Contact>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List contact categories. Requires `organization_id` query param.
     
     - parameter organizationId: (query)  
     - returns: ContactCategoryListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listContactCategories(organizationId: String) async throws -> ContactCategoryListResponse {
        return try await listContactCategoriesWithRequestBuilder(organizationId: organizationId).execute().body
    }

    /**
     List contact categories. Requires `organization_id` query param.
     - GET /v1/contacts/categories
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter organizationId: (query)  
     - returns: RequestBuilder<ContactCategoryListResponse> 
     */
    open class func listContactCategoriesWithRequestBuilder(organizationId: String) -> RequestBuilder<ContactCategoryListResponse> {
        let localVariablePath = "/v1/contacts/categories"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "organization_id": (wrappedValue: organizationId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ContactCategoryListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List supported contact providers (native + OAuth-connected).
     
     - returns: ContactProviderListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listContactProviders() async throws -> ContactProviderListResponse {
        return try await listContactProvidersWithRequestBuilder().execute().body
    }

    /**
     List supported contact providers (native + OAuth-connected).
     - GET /v1/contacts/providers
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<ContactProviderListResponse> 
     */
    open class func listContactProvidersWithRequestBuilder() -> RequestBuilder<ContactProviderListResponse> {
        let localVariablePath = "/v1/contacts/providers"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ContactProviderListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List the caller's contacts (across providers).
     
     - parameter limit: (query)  (optional)
     - parameter provider: (query)  (optional)
     - parameter search: (query)  (optional)
     - returns: ContactListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listContacts(limit: Int? = nil, provider: String? = nil, search: String? = nil) async throws -> ContactListResponse {
        return try await listContactsWithRequestBuilder(limit: limit, provider: provider, search: search).execute().body
    }

    /**
     List the caller's contacts (across providers).
     - GET /v1/contacts
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter limit: (query)  (optional)
     - parameter provider: (query)  (optional)
     - parameter search: (query)  (optional)
     - returns: RequestBuilder<ContactListResponse> 
     */
    open class func listContactsWithRequestBuilder(limit: Int? = nil, provider: String? = nil, search: String? = nil) -> RequestBuilder<ContactListResponse> {
        let localVariablePath = "/v1/contacts"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "provider": (wrappedValue: provider?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ContactListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Remove a category from a contact.
     
     - parameter id: (path)  
     - parameter categoryId: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func unassignContactCategory(id: String, categoryId: String) async throws {
        return try await unassignContactCategoryWithRequestBuilder(id: id, categoryId: categoryId).execute().body
    }

    /**
     Remove a category from a contact.
     - DELETE /v1/contacts/{id}/categories/{categoryId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter categoryId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func unassignContactCategoryWithRequestBuilder(id: String, categoryId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/contacts/{id}/categories/{categoryId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let categoryIdPreEscape = "\(APIHelper.mapValueToPathItem(categoryId))"
        let categoryIdPostEscape = categoryIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{categoryId}", with: categoryIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a contact.
     
     - parameter id: (path)  
     - parameter updateContactRequest: (body)  
     - returns: Contact
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateContact(id: String, updateContactRequest: UpdateContactRequest) async throws -> Contact {
        return try await updateContactWithRequestBuilder(id: id, updateContactRequest: updateContactRequest).execute().body
    }

    /**
     Update a contact.
     - PATCH /v1/contacts/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateContactRequest: (body)  
     - returns: RequestBuilder<Contact> 
     */
    open class func updateContactWithRequestBuilder(id: String, updateContactRequest: UpdateContactRequest) -> RequestBuilder<Contact> {
        var localVariablePath = "/v1/contacts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateContactRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Contact>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a category.
     
     - parameter id: (path)  
     - parameter updateContactCategoryRequest: (body)  
     - returns: ContactCategory
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateContactCategory(id: String, updateContactCategoryRequest: UpdateContactCategoryRequest) async throws -> ContactCategory {
        return try await updateContactCategoryWithRequestBuilder(id: id, updateContactCategoryRequest: updateContactCategoryRequest).execute().body
    }

    /**
     Update a category.
     - PATCH /v1/contacts/categories/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateContactCategoryRequest: (body)  
     - returns: RequestBuilder<ContactCategory> 
     */
    open class func updateContactCategoryWithRequestBuilder(id: String, updateContactCategoryRequest: UpdateContactCategoryRequest) -> RequestBuilder<ContactCategory> {
        var localVariablePath = "/v1/contacts/categories/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateContactCategoryRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ContactCategory>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
