//
// OAuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class OAuthAPI {

    /**
     JSON Web Key Set for id_token verification (RFC 7517).
     
     - returns: JWKS
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getJWKS() async throws -> JWKS {
        return try await getJWKSWithRequestBuilder().execute().body
    }

    /**
     JSON Web Key Set for id_token verification (RFC 7517).
     - GET /.well-known/jwks.json
     - The set of public keys RPs use to verify Spatio-issued id_tokens. Cached for 5 minutes at the edge. Always includes the currently-active signing key plus any retired keys that may still be in circulation (id_token TTL is 1 hour + slack). 
     - returns: RequestBuilder<JWKS> 
     */
    open class func getJWKSWithRequestBuilder() -> RequestBuilder<JWKS> {
        let localVariablePath = "/.well-known/jwks.json"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JWKS>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     OAuth 2.1 authorization server metadata (RFC 8414).
     
     - returns: DiscoveryDocument
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOAuthDiscovery() async throws -> DiscoveryDocument {
        return try await getOAuthDiscoveryWithRequestBuilder().execute().body
    }

    /**
     OAuth 2.1 authorization server metadata (RFC 8414).
     - GET /.well-known/oauth-authorization-server
     - Returns the canonical metadata for the Spatio OAuth 2.1 + OpenID Connect server. Third-party RPs use this to auto-discover endpoint URLs, supported scopes, and signing algorithms.  Identical payload to `/.well-known/openid-configuration` — either path is acceptable; OIDC clients prefer the openid-configuration alias. 
     - returns: RequestBuilder<DiscoveryDocument> 
     */
    open class func getOAuthDiscoveryWithRequestBuilder() -> RequestBuilder<DiscoveryDocument> {
        let localVariablePath = "/.well-known/oauth-authorization-server"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DiscoveryDocument>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     OpenID Connect Discovery 1.0 metadata.
     
     - returns: DiscoveryDocument
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOpenIDConfiguration() async throws -> DiscoveryDocument {
        return try await getOpenIDConfigurationWithRequestBuilder().execute().body
    }

    /**
     OpenID Connect Discovery 1.0 metadata.
     - GET /.well-known/openid-configuration
     - Alias of `/.well-known/oauth-authorization-server`. Provided so OIDC client libraries (NextAuth, Auth.js, oidc-client-ts, passport-openidconnect) auto-detect Spatio as an OIDC provider via their `wellKnown` / `discoveryUrl` config field. 
     - returns: RequestBuilder<DiscoveryDocument> 
     */
    open class func getOpenIDConfigurationWithRequestBuilder() -> RequestBuilder<DiscoveryDocument> {
        let localVariablePath = "/.well-known/openid-configuration"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DiscoveryDocument>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     OIDC UserInfo (OpenID Connect Core 1.0 §5.3).
     
     - returns: UserInfoResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUserInfo() async throws -> UserInfoResponse {
        return try await getUserInfoWithRequestBuilder().execute().body
    }

    /**
     OIDC UserInfo (OpenID Connect Core 1.0 §5.3).
     - GET /oauth2/userinfo
     - Returns user claims gated by the scopes on the presenting access token. `sub` is always returned; `email`, `name`, etc. require their respective scopes. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<UserInfoResponse> 
     */
    open class func getUserInfoWithRequestBuilder() -> RequestBuilder<UserInfoResponse> {
        let localVariablePath = "/oauth2/userinfo"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserInfoResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter responseType
     */
    public enum ResponseType_oauthAuthorize: String, CaseIterable {
        case code = "code"
    }

    /**
     * enum for parameter codeChallengeMethod
     */
    public enum CodeChallengeMethod_oauthAuthorize: String, CaseIterable {
        case s256 = "S256"
    }

    /**
     * enum for parameter prompt
     */
    public enum Prompt_oauthAuthorize: String, CaseIterable {
        case _none = "none"
        case login = "login"
        case consent = "consent"
    }

    /**
     OAuth 2.1 authorization endpoint (RFC 6749 + 7636 PKCE).
     
     - parameter clientId: (query)  
     - parameter redirectUri: (query)  
     - parameter responseType: (query)  
     - parameter codeChallenge: (query)  
     - parameter codeChallengeMethod: (query)  
     - parameter scope: (query)  (optional)
     - parameter state: (query)  (optional)
     - parameter nonce: (query)  (optional)
     - parameter prompt: (query)  (optional)
     - parameter maxAge: (query)  (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func oauthAuthorize(clientId: String, redirectUri: String, responseType: ResponseType_oauthAuthorize, codeChallenge: String, codeChallengeMethod: CodeChallengeMethod_oauthAuthorize, scope: String? = nil, state: String? = nil, nonce: String? = nil, prompt: Prompt_oauthAuthorize? = nil, maxAge: Int? = nil) async throws {
        return try await oauthAuthorizeWithRequestBuilder(clientId: clientId, redirectUri: redirectUri, responseType: responseType, codeChallenge: codeChallenge, codeChallengeMethod: codeChallengeMethod, scope: scope, state: state, nonce: nonce, prompt: prompt, maxAge: maxAge).execute().body
    }

    /**
     OAuth 2.1 authorization endpoint (RFC 6749 + 7636 PKCE).
     - GET /oauth2/authorize
     - Browser-redirect endpoint. Validates the client + redirect_uri, packs the request into a signed JWT, and 302s the user's browser to the consent UI. The consent UI then POSTs to `/oauth2/authorize/confirm` with the user's decision.  OIDC additions: `scope=openid+profile+email`, `nonce`, `prompt` (none|login|consent), `max_age`. 
     - parameter clientId: (query)  
     - parameter redirectUri: (query)  
     - parameter responseType: (query)  
     - parameter codeChallenge: (query)  
     - parameter codeChallengeMethod: (query)  
     - parameter scope: (query)  (optional)
     - parameter state: (query)  (optional)
     - parameter nonce: (query)  (optional)
     - parameter prompt: (query)  (optional)
     - parameter maxAge: (query)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func oauthAuthorizeWithRequestBuilder(clientId: String, redirectUri: String, responseType: ResponseType_oauthAuthorize, codeChallenge: String, codeChallengeMethod: CodeChallengeMethod_oauthAuthorize, scope: String? = nil, state: String? = nil, nonce: String? = nil, prompt: Prompt_oauthAuthorize? = nil, maxAge: Int? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/oauth2/authorize"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "client_id": (wrappedValue: clientId.encodeToJSON(), isExplode: true),
            "redirect_uri": (wrappedValue: redirectUri.encodeToJSON(), isExplode: true),
            "response_type": (wrappedValue: responseType.encodeToJSON(), isExplode: true),
            "scope": (wrappedValue: scope?.encodeToJSON(), isExplode: true),
            "state": (wrappedValue: state?.encodeToJSON(), isExplode: true),
            "code_challenge": (wrappedValue: codeChallenge.encodeToJSON(), isExplode: true),
            "code_challenge_method": (wrappedValue: codeChallengeMethod.encodeToJSON(), isExplode: true),
            "nonce": (wrappedValue: nonce?.encodeToJSON(), isExplode: true),
            "prompt": (wrappedValue: prompt?.encodeToJSON(), isExplode: true),
            "max_age": (wrappedValue: maxAge?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     RFC 7662 token introspection. Accepts both OAuth access tokens and PATs.
     
     - parameter token: (form)  
     - returns: IntrospectionResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func oauthIntrospect(token: String) async throws -> IntrospectionResponse {
        return try await oauthIntrospectWithRequestBuilder(token: token).execute().body
    }

    /**
     RFC 7662 token introspection. Accepts both OAuth access tokens and PATs.
     - POST /oauth2/introspect
     - parameter token: (form)  
     - returns: RequestBuilder<IntrospectionResponse> 
     */
    open class func oauthIntrospectWithRequestBuilder(token: String) -> RequestBuilder<IntrospectionResponse> {
        let localVariablePath = "/oauth2/introspect"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "token": token.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IntrospectionResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     RFC 7009 token revocation. Idempotent.
     
     - parameter token: (form)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func oauthRevoke(token: String) async throws {
        return try await oauthRevokeWithRequestBuilder(token: token).execute().body
    }

    /**
     RFC 7009 token revocation. Idempotent.
     - POST /oauth2/revoke
     - parameter token: (form)  
     - returns: RequestBuilder<Void> 
     */
    open class func oauthRevokeWithRequestBuilder(token: String) -> RequestBuilder<Void> {
        let localVariablePath = "/oauth2/revoke"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "token": token.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter grantType
     */
    public enum GrantType_oauthToken: String, CaseIterable {
        case authorizationCode = "authorization_code"
        case refreshToken = "refresh_token"
    }

    /**
     Exchange authorization code or refresh token for an access token (+ id_token if `openid` scope).
     
     - parameter grantType: (form)  
     - parameter code: (form) Required for authorization_code grant. (optional)
     - parameter codeVerifier: (form) PKCE verifier — required for authorization_code grant. (optional)
     - parameter redirectUri: (form)  (optional)
     - parameter refreshToken: (form) Required for refresh_token grant. (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - returns: TokenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func oauthToken(grantType: GrantType_oauthToken, code: String? = nil, codeVerifier: String? = nil, redirectUri: String? = nil, refreshToken: String? = nil, clientId: String? = nil, clientSecret: String? = nil) async throws -> TokenResponse {
        return try await oauthTokenWithRequestBuilder(grantType: grantType, code: code, codeVerifier: codeVerifier, redirectUri: redirectUri, refreshToken: refreshToken, clientId: clientId, clientSecret: clientSecret).execute().body
    }

    /**
     Exchange authorization code or refresh token for an access token (+ id_token if `openid` scope).
     - POST /oauth2/token
     - parameter grantType: (form)  
     - parameter code: (form) Required for authorization_code grant. (optional)
     - parameter codeVerifier: (form) PKCE verifier — required for authorization_code grant. (optional)
     - parameter redirectUri: (form)  (optional)
     - parameter refreshToken: (form) Required for refresh_token grant. (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - returns: RequestBuilder<TokenResponse> 
     */
    open class func oauthTokenWithRequestBuilder(grantType: GrantType_oauthToken, code: String? = nil, codeVerifier: String? = nil, redirectUri: String? = nil, refreshToken: String? = nil, clientId: String? = nil, clientSecret: String? = nil) -> RequestBuilder<TokenResponse> {
        let localVariablePath = "/oauth2/token"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "grant_type": grantType.encodeToJSON(),
            "code": code?.encodeToJSON(),
            "code_verifier": codeVerifier?.encodeToJSON(),
            "redirect_uri": redirectUri?.encodeToJSON(),
            "refresh_token": refreshToken?.encodeToJSON(),
            "client_id": clientId?.encodeToJSON(),
            "client_secret": clientSecret?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TokenResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Same as GET /oauth2/userinfo. Provided for clients that send the bearer in the body.
     
     - returns: UserInfoResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postUserInfo() async throws -> UserInfoResponse {
        return try await postUserInfoWithRequestBuilder().execute().body
    }

    /**
     Same as GET /oauth2/userinfo. Provided for clients that send the bearer in the body.
     - POST /oauth2/userinfo
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<UserInfoResponse> 
     */
    open class func postUserInfoWithRequestBuilder() -> RequestBuilder<UserInfoResponse> {
        let localVariablePath = "/oauth2/userinfo"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserInfoResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Register a new OAuth 2.1 client (RFC 7591 dynamic client registration).
     
     - parameter clientRegistrationRequest: (body)  
     - returns: ClientRegistrationResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func registerOAuthClient(clientRegistrationRequest: ClientRegistrationRequest) async throws -> ClientRegistrationResponse {
        return try await registerOAuthClientWithRequestBuilder(clientRegistrationRequest: clientRegistrationRequest).execute().body
    }

    /**
     Register a new OAuth 2.1 client (RFC 7591 dynamic client registration).
     - POST /oauth2/register
     - Returns a fresh `client_id` (and, for confidential clients, `client_secret`) plus a one-time `registration_access_token` the client can use later to update its registration. Public clients (mobile, SPA) MUST use `token_endpoint_auth_method: none` and PKCE.  Rate-limited to 10 registrations per hour per source IP. 
     - parameter clientRegistrationRequest: (body)  
     - returns: RequestBuilder<ClientRegistrationResponse> 
     */
    open class func registerOAuthClientWithRequestBuilder(clientRegistrationRequest: ClientRegistrationRequest) -> RequestBuilder<ClientRegistrationResponse> {
        let localVariablePath = "/oauth2/register"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: clientRegistrationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ClientRegistrationResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
