//
// RecordsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RecordsAPI {

    /**
     Create a record.
     
     - parameter createRecordRequest: (body)  
     - returns: Record
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createRecord(createRecordRequest: CreateRecordRequest) async throws -> Record {
        return try await createRecordWithRequestBuilder(createRecordRequest: createRecordRequest).execute().body
    }

    /**
     Create a record.
     - POST /v1/records
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createRecordRequest: (body)  
     - returns: RequestBuilder<Record> 
     */
    open class func createRecordWithRequestBuilder(createRecordRequest: CreateRecordRequest) -> RequestBuilder<Record> {
        let localVariablePath = "/v1/records"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createRecordRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Record>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create a record type (org-scoped).
     
     - parameter createRecordTypeRequest: (body)  
     - returns: RecordType
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createRecordType(createRecordTypeRequest: CreateRecordTypeRequest) async throws -> RecordType {
        return try await createRecordTypeWithRequestBuilder(createRecordTypeRequest: createRecordTypeRequest).execute().body
    }

    /**
     Create a record type (org-scoped).
     - POST /v1/records/types
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createRecordTypeRequest: (body)  
     - returns: RequestBuilder<RecordType> 
     */
    open class func createRecordTypeWithRequestBuilder(createRecordTypeRequest: CreateRecordTypeRequest) -> RequestBuilder<RecordType> {
        let localVariablePath = "/v1/records/types"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createRecordTypeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecordType>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a record.
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteRecord(id: String) async throws {
        return try await deleteRecordWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete a record.
     - DELETE /v1/records/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteRecordWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/records/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch a record.
     
     - parameter id: (path)  
     - returns: Record
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRecord(id: String) async throws -> Record {
        return try await getRecordWithRequestBuilder(id: id).execute().body
    }

    /**
     Fetch a record.
     - GET /v1/records/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Record> 
     */
    open class func getRecordWithRequestBuilder(id: String) -> RequestBuilder<Record> {
        var localVariablePath = "/v1/records/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Record>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List record types for an organization.
     
     - parameter organizationId: (query)  
     - returns: RecordTypeListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listRecordTypes(organizationId: String) async throws -> RecordTypeListResponse {
        return try await listRecordTypesWithRequestBuilder(organizationId: organizationId).execute().body
    }

    /**
     List record types for an organization.
     - GET /v1/records/types
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter organizationId: (query)  
     - returns: RequestBuilder<RecordTypeListResponse> 
     */
    open class func listRecordTypesWithRequestBuilder(organizationId: String) -> RequestBuilder<RecordTypeListResponse> {
        let localVariablePath = "/v1/records/types"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "organization_id": (wrappedValue: organizationId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecordTypeListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List records for an organization. `organization_id` query param is required (handler returns 400 otherwise). 
     
     - parameter organizationId: (query)  
     - parameter recordTypeId: (query)  (optional)
     - parameter limit: (query)  (optional)
     - returns: RecordListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listRecords(organizationId: String, recordTypeId: String? = nil, limit: Int? = nil) async throws -> RecordListResponse {
        return try await listRecordsWithRequestBuilder(organizationId: organizationId, recordTypeId: recordTypeId, limit: limit).execute().body
    }

    /**
     List records for an organization. `organization_id` query param is required (handler returns 400 otherwise). 
     - GET /v1/records
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter organizationId: (query)  
     - parameter recordTypeId: (query)  (optional)
     - parameter limit: (query)  (optional)
     - returns: RequestBuilder<RecordListResponse> 
     */
    open class func listRecordsWithRequestBuilder(organizationId: String, recordTypeId: String? = nil, limit: Int? = nil) -> RequestBuilder<RecordListResponse> {
        let localVariablePath = "/v1/records"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "organization_id": (wrappedValue: organizationId.encodeToJSON(), isExplode: true),
            "record_type_id": (wrappedValue: recordTypeId?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecordListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a record.
     
     - parameter id: (path)  
     - parameter updateRecordRequest: (body)  
     - returns: Record
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateRecord(id: String, updateRecordRequest: UpdateRecordRequest) async throws -> Record {
        return try await updateRecordWithRequestBuilder(id: id, updateRecordRequest: updateRecordRequest).execute().body
    }

    /**
     Update a record.
     - PATCH /v1/records/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateRecordRequest: (body)  
     - returns: RequestBuilder<Record> 
     */
    open class func updateRecordWithRequestBuilder(id: String, updateRecordRequest: UpdateRecordRequest) -> RequestBuilder<Record> {
        var localVariablePath = "/v1/records/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateRecordRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Record>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a record type.
     
     - parameter id: (path)  
     - parameter updateRecordTypeRequest: (body)  
     - returns: RecordType
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateRecordType(id: String, updateRecordTypeRequest: UpdateRecordTypeRequest) async throws -> RecordType {
        return try await updateRecordTypeWithRequestBuilder(id: id, updateRecordTypeRequest: updateRecordTypeRequest).execute().body
    }

    /**
     Update a record type.
     - PATCH /v1/records/types/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateRecordTypeRequest: (body)  
     - returns: RequestBuilder<RecordType> 
     */
    open class func updateRecordTypeWithRequestBuilder(id: String, updateRecordTypeRequest: UpdateRecordTypeRequest) -> RequestBuilder<RecordType> {
        var localVariablePath = "/v1/records/types/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateRecordTypeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecordType>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
