//
// RecommendationsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RecommendationsAPI {

    /**
     Delete a recommendation (hard delete; status-update is preferred).
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteRecommendation(id: String) async throws {
        return try await deleteRecommendationWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete a recommendation (hard delete; status-update is preferred).
     - DELETE /v1/recommendations/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteRecommendationWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/recommendations/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch one recommendation.
     
     - parameter id: (path)  
     - returns: Recommendation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRecommendation(id: String) async throws -> Recommendation {
        return try await getRecommendationWithRequestBuilder(id: id).execute().body
    }

    /**
     Fetch one recommendation.
     - GET /v1/recommendations/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Recommendation> 
     */
    open class func getRecommendationWithRequestBuilder(id: String) -> RequestBuilder<Recommendation> {
        var localVariablePath = "/v1/recommendations/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Recommendation>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List recommendations for a workspace.
     
     - parameter workspaceId: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter limit: (query)  (optional)
     - returns: RecommendationListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listRecommendations(workspaceId: String? = nil, status: String? = nil, limit: Int? = nil) async throws -> RecommendationListResponse {
        return try await listRecommendationsWithRequestBuilder(workspaceId: workspaceId, status: status, limit: limit).execute().body
    }

    /**
     List recommendations for a workspace.
     - GET /v1/recommendations
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter workspaceId: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter limit: (query)  (optional)
     - returns: RequestBuilder<RecommendationListResponse> 
     */
    open class func listRecommendationsWithRequestBuilder(workspaceId: String? = nil, status: String? = nil, limit: Int? = nil) -> RequestBuilder<RecommendationListResponse> {
        let localVariablePath = "/v1/recommendations"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "workspaceId": (wrappedValue: workspaceId?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecommendationListResponse>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Agent-side propose endpoint (the `spatio_recommendations propose` MCP tool calls this).
     
     - parameter proposeRecommendationRequest: (body)  
     - returns: Recommendation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func proposeRecommendation(proposeRecommendationRequest: ProposeRecommendationRequest) async throws -> Recommendation {
        return try await proposeRecommendationWithRequestBuilder(proposeRecommendationRequest: proposeRecommendationRequest).execute().body
    }

    /**
     Agent-side propose endpoint (the `spatio_recommendations propose` MCP tool calls this).
     - POST /v1/recommendations
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter proposeRecommendationRequest: (body)  
     - returns: RequestBuilder<Recommendation> 
     */
    open class func proposeRecommendationWithRequestBuilder(proposeRecommendationRequest: ProposeRecommendationRequest) -> RequestBuilder<Recommendation> {
        let localVariablePath = "/v1/recommendations"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: proposeRecommendationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Recommendation>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Accept or dismiss a recommendation.
     
     - parameter id: (path)  
     - parameter updateRecommendationStatusRequest: (body)  
     - returns: Recommendation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateRecommendationStatus(id: String, updateRecommendationStatusRequest: UpdateRecommendationStatusRequest) async throws -> Recommendation {
        return try await updateRecommendationStatusWithRequestBuilder(id: id, updateRecommendationStatusRequest: updateRecommendationStatusRequest).execute().body
    }

    /**
     Accept or dismiss a recommendation.
     - PATCH /v1/recommendations/{id}/status
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter updateRecommendationStatusRequest: (body)  
     - returns: RequestBuilder<Recommendation> 
     */
    open class func updateRecommendationStatusWithRequestBuilder(id: String, updateRecommendationStatusRequest: UpdateRecommendationStatusRequest) -> RequestBuilder<Recommendation> {
        var localVariablePath = "/v1/recommendations/{id}/status"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateRecommendationStatusRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Recommendation>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
