//
// ResourcesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ResourcesAPI {

    /**
     List access grants on a resource (per-resource ACL).
     
     - parameter platform: (path)  
     - parameter resourceId: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listResourcePermissionGrants(platform: String, resourceId: String) async throws -> [String: AnyCodable] {
        return try await listResourcePermissionGrantsWithRequestBuilder(platform: platform, resourceId: resourceId).execute().body
    }

    /**
     List access grants on a resource (per-resource ACL).
     - GET /v1/resources/{platform}/{resourceId}/permissions
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter platform: (path)  
     - parameter resourceId: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func listResourcePermissionGrantsWithRequestBuilder(platform: String, resourceId: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/resources/{platform}/{resourceId}/permissions"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let resourceIdPreEscape = "\(APIHelper.mapValueToPathItem(resourceId))"
        let resourceIdPostEscape = resourceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resourceId}", with: resourceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Revoke an access grant.
     
     - parameter platform: (path)  
     - parameter resourceId: (path)  
     - parameter grantId: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func revokeResourcePermissionGrant(platform: String, resourceId: String, grantId: String) async throws {
        return try await revokeResourcePermissionGrantWithRequestBuilder(platform: platform, resourceId: resourceId, grantId: grantId).execute().body
    }

    /**
     Revoke an access grant.
     - DELETE /v1/resources/{platform}/{resourceId}/permissions/{grantId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter platform: (path)  
     - parameter resourceId: (path)  
     - parameter grantId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func revokeResourcePermissionGrantWithRequestBuilder(platform: String, resourceId: String, grantId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/resources/{platform}/{resourceId}/permissions/{grantId}"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let resourceIdPreEscape = "\(APIHelper.mapValueToPathItem(resourceId))"
        let resourceIdPostEscape = resourceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resourceId}", with: resourceIdPostEscape, options: .literal, range: nil)
        let grantIdPreEscape = "\(APIHelper.mapValueToPathItem(grantId))"
        let grantIdPostEscape = grantIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{grantId}", with: grantIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create or update an access grant.
     
     - parameter platform: (path)  
     - parameter resourceId: (path)  
     - parameter requestBody: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setResourcePermissionGrant(platform: String, resourceId: String, requestBody: [String: AnyCodable]) async throws -> [String: AnyCodable] {
        return try await setResourcePermissionGrantWithRequestBuilder(platform: platform, resourceId: resourceId, requestBody: requestBody).execute().body
    }

    /**
     Create or update an access grant.
     - POST /v1/resources/{platform}/{resourceId}/permissions
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter platform: (path)  
     - parameter resourceId: (path)  
     - parameter requestBody: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func setResourcePermissionGrantWithRequestBuilder(platform: String, resourceId: String, requestBody: [String: AnyCodable]) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/resources/{platform}/{resourceId}/permissions"
        let platformPreEscape = "\(APIHelper.mapValueToPathItem(platform))"
        let platformPostEscape = platformPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{platform}", with: platformPostEscape, options: .literal, range: nil)
        let resourceIdPreEscape = "\(APIHelper.mapValueToPathItem(resourceId))"
        let resourceIdPostEscape = resourceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{resourceId}", with: resourceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
