//
// SearchAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SearchAPI {

    /**
     Cross-platform federated search.
     
     - parameter federatedSearchRequest: (body)  
     - returns: FederatedSearch200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func federatedSearch(federatedSearchRequest: FederatedSearchRequest) async throws -> FederatedSearch200Response {
        return try await federatedSearchWithRequestBuilder(federatedSearchRequest: federatedSearchRequest).execute().body
    }

    /**
     Cross-platform federated search.
     - POST /v1/search
     - Fans out to every platform's per-platform search method in parallel, merges + dedupes results, and returns them in a relevance-then-recency ranking with per-platform cursors for pagination. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter federatedSearchRequest: (body)  
     - returns: RequestBuilder<FederatedSearch200Response> 
     */
    open class func federatedSearchWithRequestBuilder(federatedSearchRequest: FederatedSearchRequest) -> RequestBuilder<FederatedSearch200Response> {
        let localVariablePath = "/v1/search"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: federatedSearchRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FederatedSearch200Response>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
