//
// SheetsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SheetsAPI {

    /**
     Create a sheet.
     
     - parameter createSheetRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Sheet
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createSheet(createSheetRequest: CreateSheetRequest, accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil) async throws -> Sheet {
        return try await createSheetWithRequestBuilder(createSheetRequest: createSheetRequest, accountId: accountId, provider: provider, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Create a sheet.
     - POST /v1/sheets
     - Creates a new sheet under the target account. Target resolution mirrors `POST /v1/notes`: body `accountId` → `?accountId=` → body `provider` → `?provider=` → caller's single connected account (errors with `ambiguous_account` if more than one is connected and no selector is supplied). 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createSheetRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Sheet> 
     */
    open class func createSheetWithRequestBuilder(createSheetRequest: CreateSheetRequest, accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Sheet> {
        let localVariablePath = "/v1/sheets"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createSheetRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
            "provider": (wrappedValue: provider?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Sheet>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Insert a row.
     
     - parameter id: (path) Sheet id. 
     - parameter createRowRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Row
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createSheetRow(id: String, createRowRequest: CreateRowRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Row {
        return try await createSheetRowWithRequestBuilder(id: id, createRowRequest: createRowRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Insert a row.
     - POST /v1/sheets/{id}/rows
     - Inserts a row at `index` (zero-based) or appends to the end when `index` is omitted. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter createRowRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Row> 
     */
    open class func createSheetRowWithRequestBuilder(id: String, createRowRequest: CreateRowRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Row> {
        var localVariablePath = "/v1/sheets/{id}/rows"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createRowRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Row>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a sheet.
     
     - parameter id: (path) Sheet id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SuccessFlag
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteSheet(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SuccessFlag {
        return try await deleteSheetWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Delete a sheet.
     - DELETE /v1/sheets/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SuccessFlag> 
     */
    open class func deleteSheetWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SuccessFlag> {
        var localVariablePath = "/v1/sheets/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessFlag>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a row.
     
     - parameter id: (path) Sheet id. 
     - parameter rowIndex: (path) Zero-based row index. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SuccessFlag
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteSheetRow(id: String, rowIndex: Int, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SuccessFlag {
        return try await deleteSheetRowWithRequestBuilder(id: id, rowIndex: rowIndex, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Delete a row.
     - DELETE /v1/sheets/{id}/rows/{rowIndex}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter rowIndex: (path) Zero-based row index. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SuccessFlag> 
     */
    open class func deleteSheetRowWithRequestBuilder(id: String, rowIndex: Int, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SuccessFlag> {
        var localVariablePath = "/v1/sheets/{id}/rows/{rowIndex}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let rowIndexPreEscape = "\(APIHelper.mapValueToPathItem(rowIndex))"
        let rowIndexPostEscape = rowIndexPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{rowIndex}", with: rowIndexPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessFlag>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch one sheet.
     
     - parameter id: (path) Sheet id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Sheet
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSheet(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Sheet {
        return try await getSheetWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Fetch one sheet.
     - GET /v1/sheets/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Sheet> 
     */
    open class func getSheetWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Sheet> {
        var localVariablePath = "/v1/sheets/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Sheet>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List rows in a sheet.
     
     - parameter id: (path) Sheet id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RowList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listSheetRows(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, limit: Int? = nil, offset: Int? = nil) async throws -> RowList {
        return try await listSheetRowsWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID, limit: limit, offset: offset).execute().body
    }

    /**
     List rows in a sheet.
     - GET /v1/sheets/{id}/rows
     - Single-account row list. Unlike `GET /v1/sheets`, row listing always targets the one account that owns the sheet, so the response is a plain `{ rows, total }` rather than a fan-out envelope. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<RowList> 
     */
    open class func listSheetRowsWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<RowList> {
        var localVariablePath = "/v1/sheets/{id}/rows"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RowList>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List sheets across connected accounts.
     
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - returns: SheetListEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listSheets(accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil, limit: Int? = nil, offset: Int? = nil) async throws -> SheetListEnvelope {
        return try await listSheetsWithRequestBuilder(accountId: accountId, provider: provider, xWorkspaceID: xWorkspaceID, limit: limit, offset: offset).execute().body
    }

    /**
     List sheets across connected accounts.
     - GET /v1/sheets
     - Fan-out list. Returns every sheet visible to the caller across every connected sheets provider, paginated by `limit` / `offset`. Pass `?accountId=` or `?provider=` to scope to a single source. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<SheetListEnvelope> 
     */
    open class func listSheetsWithRequestBuilder(accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<SheetListEnvelope> {
        let localVariablePath = "/v1/sheets"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
            "provider": (wrappedValue: provider?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SheetListEnvelope>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a sheet (partial).
     
     - parameter id: (path) Sheet id. 
     - parameter updateSheetRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Sheet
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateSheet(id: String, updateSheetRequest: UpdateSheetRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Sheet {
        return try await updateSheetWithRequestBuilder(id: id, updateSheetRequest: updateSheetRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Update a sheet (partial).
     - PATCH /v1/sheets/{id}
     - Partial update of sheet metadata. The renderer also calls this via `PUT /v1/sheets/{id}` for autosave parity; both verbs invoke the same handler. Per-cell and per-row mutations live on their dedicated endpoints, not here. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter updateSheetRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Sheet> 
     */
    open class func updateSheetWithRequestBuilder(id: String, updateSheetRequest: UpdateSheetRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Sheet> {
        var localVariablePath = "/v1/sheets/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateSheetRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Sheet>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a single cell.
     
     - parameter id: (path) Sheet id. 
     - parameter rowIndex: (path) Zero-based row index. 
     - parameter column: (path) Column identifier. Provider-specific — usually a letter (&#x60;A&#x60;, &#x60;AB&#x60;) for spreadsheet providers or a column key string for structured providers.  
     - parameter updateCellRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Cell
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateSheetCell(id: String, rowIndex: Int, column: String, updateCellRequest: UpdateCellRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Cell {
        return try await updateSheetCellWithRequestBuilder(id: id, rowIndex: rowIndex, column: column, updateCellRequest: updateCellRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Update a single cell.
     - PATCH /v1/sheets/{id}/rows/{rowIndex}/cells/{column}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter rowIndex: (path) Zero-based row index. 
     - parameter column: (path) Column identifier. Provider-specific — usually a letter (&#x60;A&#x60;, &#x60;AB&#x60;) for spreadsheet providers or a column key string for structured providers.  
     - parameter updateCellRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Cell> 
     */
    open class func updateSheetCellWithRequestBuilder(id: String, rowIndex: Int, column: String, updateCellRequest: UpdateCellRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Cell> {
        var localVariablePath = "/v1/sheets/{id}/rows/{rowIndex}/cells/{column}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let rowIndexPreEscape = "\(APIHelper.mapValueToPathItem(rowIndex))"
        let rowIndexPostEscape = rowIndexPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{rowIndex}", with: rowIndexPostEscape, options: .literal, range: nil)
        let columnPreEscape = "\(APIHelper.mapValueToPathItem(column))"
        let columnPostEscape = columnPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{column}", with: columnPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateCellRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Cell>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a row (sparse).
     
     - parameter id: (path) Sheet id. 
     - parameter rowIndex: (path) Zero-based row index. 
     - parameter updateRowRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Row
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateSheetRow(id: String, rowIndex: Int, updateRowRequest: UpdateRowRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Row {
        return try await updateSheetRowWithRequestBuilder(id: id, rowIndex: rowIndex, updateRowRequest: updateRowRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Update a row (sparse).
     - PATCH /v1/sheets/{id}/rows/{rowIndex}
     - Sparse update — keys present in `cells` overwrite that column; keys absent are preserved. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Sheet id. 
     - parameter rowIndex: (path) Zero-based row index. 
     - parameter updateRowRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Row> 
     */
    open class func updateSheetRowWithRequestBuilder(id: String, rowIndex: Int, updateRowRequest: UpdateRowRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Row> {
        var localVariablePath = "/v1/sheets/{id}/rows/{rowIndex}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let rowIndexPreEscape = "\(APIHelper.mapValueToPathItem(rowIndex))"
        let rowIndexPostEscape = rowIndexPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{rowIndex}", with: rowIndexPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateRowRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Row>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
