//
// SlidesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SlidesAPI {

    /**
     Create a presentation.
     
     - parameter createPresentationRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Presentation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createPresentation(createPresentationRequest: CreatePresentationRequest, accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil) async throws -> Presentation {
        return try await createPresentationWithRequestBuilder(createPresentationRequest: createPresentationRequest, accountId: accountId, provider: provider, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Create a presentation.
     - POST /v1/slides
     - Creates a new deck under the target account. Target resolution mirrors `POST /v1/notes` and `/v1/sheets`: body `accountId` → `?accountId=` → body `provider` → `?provider=` → caller's single connected account (errors with `ambiguous_account` otherwise). The new deck is auto-seeded with one blank slide so the renderer has something to display immediately. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter createPresentationRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Presentation> 
     */
    open class func createPresentationWithRequestBuilder(createPresentationRequest: CreatePresentationRequest, accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Presentation> {
        let localVariablePath = "/v1/slides"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createPresentationRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
            "provider": (wrappedValue: provider?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Presentation>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Insert a slide.
     
     - parameter id: (path) Presentation id. 
     - parameter createSlideRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Slide
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createSlide(id: String, createSlideRequest: CreateSlideRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Slide {
        return try await createSlideWithRequestBuilder(id: id, createSlideRequest: createSlideRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Insert a slide.
     - POST /v1/slides/{id}/slides
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter createSlideRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Slide> 
     */
    open class func createSlideWithRequestBuilder(id: String, createSlideRequest: CreateSlideRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Slide> {
        var localVariablePath = "/v1/slides/{id}/slides"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createSlideRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Slide>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Add a canvas element (text/shape/image) to a slide.
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter createSlideElementRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SlideElement
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createSlideElement(id: String, slideId: String, createSlideElementRequest: CreateSlideElementRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SlideElement {
        return try await createSlideElementWithRequestBuilder(id: id, slideId: slideId, createSlideElementRequest: createSlideElementRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Add a canvas element (text/shape/image) to a slide.
     - POST /v1/slides/{id}/slides/{slideId}/elements
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter createSlideElementRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SlideElement> 
     */
    open class func createSlideElementWithRequestBuilder(id: String, slideId: String, createSlideElementRequest: CreateSlideElementRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SlideElement> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}/elements"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createSlideElementRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SlideElement>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a presentation.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SuccessFlag
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deletePresentation(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SuccessFlag {
        return try await deletePresentationWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Delete a presentation.
     - DELETE /v1/slides/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SuccessFlag> 
     */
    open class func deletePresentationWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SuccessFlag> {
        var localVariablePath = "/v1/slides/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessFlag>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a slide.
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SuccessFlag
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteSlide(id: String, slideId: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SuccessFlag {
        return try await deleteSlideWithRequestBuilder(id: id, slideId: slideId, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Delete a slide.
     - DELETE /v1/slides/{id}/slides/{slideId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SuccessFlag> 
     */
    open class func deleteSlideWithRequestBuilder(id: String, slideId: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SuccessFlag> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessFlag>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a slide element.
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter elementId: (path) Slide-element id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SuccessFlag
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteSlideElement(id: String, slideId: String, elementId: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SuccessFlag {
        return try await deleteSlideElementWithRequestBuilder(id: id, slideId: slideId, elementId: elementId, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Delete a slide element.
     - DELETE /v1/slides/{id}/slides/{slideId}/elements/{elementId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter elementId: (path) Slide-element id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SuccessFlag> 
     */
    open class func deleteSlideElementWithRequestBuilder(id: String, slideId: String, elementId: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SuccessFlag> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}/elements/{elementId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let elementIdPreEscape = "\(APIHelper.mapValueToPathItem(elementId))"
        let elementIdPostEscape = elementIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{elementId}", with: elementIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuccessFlag>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Disable public sharing.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func disablePresentationShare(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws {
        return try await disablePresentationShareWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Disable public sharing.
     - DELETE /v1/slides/{id}/share
     - Owner-only. Subsequent public viewer requests 404.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func disablePresentationShareWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/slides/{id}/share"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Enable (or update password on) public sharing.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter enableShareRequest: (body)  (optional)
     - returns: ShareSettings
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func enablePresentationShare(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, enableShareRequest: EnableShareRequest? = nil) async throws -> ShareSettings {
        return try await enablePresentationShareWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID, enableShareRequest: enableShareRequest).execute().body
    }

    /**
     Enable (or update password on) public sharing.
     - POST /v1/slides/{id}/share
     - Owner-only. With `setPassword: false` (or empty body), flips the deck public without changing the password. With `setPassword: true`, applies `password` (empty clears). 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter enableShareRequest: (body)  (optional)
     - returns: RequestBuilder<ShareSettings> 
     */
    open class func enablePresentationShareWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, enableShareRequest: EnableShareRequest? = nil) -> RequestBuilder<ShareSettings> {
        var localVariablePath = "/v1/slides/{id}/share"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: enableShareRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ShareSettings>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter storage
     */
    public enum Storage_exportPresentationPdf: String, CaseIterable {
        case stream = "stream"
        case r2 = "r2"
    }

    /**
     Render the presentation as a PDF.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter storage: (query)  (optional, default to .stream)
     - parameter filename: (query) Sanitized base name for the downloaded PDF. (optional)
     - parameter exportPDFRequest: (body)  (optional)
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func exportPresentationPdf(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, storage: Storage_exportPresentationPdf? = nil, filename: String? = nil, exportPDFRequest: ExportPDFRequest? = nil) async throws -> URL {
        return try await exportPresentationPdfWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID, storage: storage, filename: filename, exportPDFRequest: exportPDFRequest).execute().body
    }

    /**
     Render the presentation as a PDF.
     - POST /v1/slides/{id}/export/pdf
     - Proxies to the Spatio export sidecar (Playwright). Two response modes selected via `?storage=`:    - `stream` (default) — response body is the PDF binary     (`application/pdf`).   - `r2` — uploads the rendered PDF to R2 storage and returns     a JSON envelope with a 24-hour signed URL.  Returns `503 Service Unavailable` when the export sidecar is not configured (dev fallback to the client-side exporter). 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter storage: (query)  (optional, default to .stream)
     - parameter filename: (query) Sanitized base name for the downloaded PDF. (optional)
     - parameter exportPDFRequest: (body)  (optional)
     - returns: RequestBuilder<URL> 
     */
    open class func exportPresentationPdfWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, storage: Storage_exportPresentationPdf? = nil, filename: String? = nil, exportPDFRequest: ExportPDFRequest? = nil) -> RequestBuilder<URL> {
        var localVariablePath = "/v1/slides/{id}/export/pdf"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: exportPDFRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
            "storage": (wrappedValue: storage?.encodeToJSON(), isExplode: true),
            "filename": (wrappedValue: filename?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter storage
     */
    public enum Storage_exportPresentationPptx: String, CaseIterable {
        case stream = "stream"
        case r2 = "r2"
    }

    /**
     Render the presentation as a PowerPoint (.pptx) file.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter storage: (query)  (optional, default to .stream)
     - parameter filename: (query) Sanitized base name for the downloaded PPTX. (optional)
     - parameter exportPDFRequest: (body)  (optional)
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func exportPresentationPptx(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, storage: Storage_exportPresentationPptx? = nil, filename: String? = nil, exportPDFRequest: ExportPDFRequest? = nil) async throws -> URL {
        return try await exportPresentationPptxWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID, storage: storage, filename: filename, exportPDFRequest: exportPDFRequest).execute().body
    }

    /**
     Render the presentation as a PowerPoint (.pptx) file.
     - POST /v1/slides/{id}/export/pptx
     - Proxies to the Spatio export sidecar (Playwright + pptxgenjs). Each slide is screenshotted at 2× device-pixel ratio and wrapped into a PowerPoint .pptx as a full-bleed image. Visual fidelity is preserved exactly — what renders in Spatio renders identically in PowerPoint, Keynote, Google Slides — at the cost of in-PowerPoint editability of slide content. Users edit slide content back in Spatio (the source of truth), not inside PowerPoint.  Two response modes selected via `?storage=`:    - `stream` (default) — response body is the PPTX binary     (`application/vnd.openxmlformats-officedocument.presentationml.presentation`).   - `r2` — uploads the rendered PPTX to R2 storage and returns     a JSON envelope with a 24-hour signed URL.  Returns `503 Service Unavailable` when the export sidecar is not configured. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter storage: (query)  (optional, default to .stream)
     - parameter filename: (query) Sanitized base name for the downloaded PPTX. (optional)
     - parameter exportPDFRequest: (body)  (optional)
     - returns: RequestBuilder<URL> 
     */
    open class func exportPresentationPptxWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil, storage: Storage_exportPresentationPptx? = nil, filename: String? = nil, exportPDFRequest: ExportPDFRequest? = nil) -> RequestBuilder<URL> {
        var localVariablePath = "/v1/slides/{id}/export/pptx"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: exportPDFRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
            "storage": (wrappedValue: storage?.encodeToJSON(), isExplode: true),
            "filename": (wrappedValue: filename?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch one presentation.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Presentation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPresentation(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Presentation {
        return try await getPresentationWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Fetch one presentation.
     - GET /v1/slides/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Presentation> 
     */
    open class func getPresentationWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Presentation> {
        var localVariablePath = "/v1/slides/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Presentation>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch share settings for a presentation.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: ShareSettings
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPresentationShareSettings(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> ShareSettings {
        return try await getPresentationShareSettingsWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Fetch share settings for a presentation.
     - GET /v1/slides/{id}/share
     - Owner-only. Mirror of `GET /v1/notes/{id}/share` — same shape, same fields. Returns the current public-share configuration, including the share token and computed public viewer URL when the deck is currently public. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<ShareSettings> 
     */
    open class func getPresentationShareSettingsWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<ShareSettings> {
        var localVariablePath = "/v1/slides/{id}/share"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ShareSettings>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch a publicly shared presentation.
     
     - parameter token: (path) Opaque public-share token. 
     - parameter password: (query) Optional viewer password. (optional)
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPublicPresentation(token: String, password: String? = nil) async throws -> [String: AnyCodable] {
        return try await getPublicPresentationWithRequestBuilder(token: token, password: password).execute().body
    }

    /**
     Fetch a publicly shared presentation.
     - GET /public/slides/{token}
     - Unauthenticated. Mirror of `GET /public/notes/{token}`. The share token is the credential. For password-protected decks the password is supplied via `?password=`; the response distinguishes \"no password supplied\" from \"wrong password\" so the viewer can render the right prompt. Unknown tokens and disabled-share decks both return `404` to prevent enumeration. 
     - parameter token: (path) Opaque public-share token. 
     - parameter password: (query) Optional viewer password. (optional)
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getPublicPresentationWithRequestBuilder(token: String, password: String? = nil) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/public/slides/{token}"
        let tokenPreEscape = "\(APIHelper.mapValueToPathItem(token))"
        let tokenPostEscape = tokenPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{token}", with: tokenPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "password": (wrappedValue: password?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Fetch one slide.
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Slide
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSlide(id: String, slideId: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Slide {
        return try await getSlideWithRequestBuilder(id: id, slideId: slideId, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Fetch one slide.
     - GET /v1/slides/{id}/slides/{slideId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Slide> 
     */
    open class func getSlideWithRequestBuilder(id: String, slideId: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Slide> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Slide>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch one slide element.
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter elementId: (path) Slide-element id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SlideElement
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getSlideElement(id: String, slideId: String, elementId: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SlideElement {
        return try await getSlideElementWithRequestBuilder(id: id, slideId: slideId, elementId: elementId, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Fetch one slide element.
     - GET /v1/slides/{id}/slides/{slideId}/elements/{elementId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter elementId: (path) Slide-element id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SlideElement> 
     */
    open class func getSlideElementWithRequestBuilder(id: String, slideId: String, elementId: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SlideElement> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}/elements/{elementId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let elementIdPreEscape = "\(APIHelper.mapValueToPathItem(elementId))"
        let elementIdPostEscape = elementIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{elementId}", with: elementIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SlideElement>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List presentations across connected accounts.
     
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - returns: PresentationListEnvelope
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listPresentations(accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil, limit: Int? = nil, offset: Int? = nil) async throws -> PresentationListEnvelope {
        return try await listPresentationsWithRequestBuilder(accountId: accountId, provider: provider, xWorkspaceID: xWorkspaceID, limit: limit, offset: offset).execute().body
    }

    /**
     List presentations across connected accounts.
     - GET /v1/slides
     - Fan-out list. Returns every presentation visible to the caller across every connected slides provider. Pass `?accountId=` or `?provider=` to scope to a single source. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter provider: (query) Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - parameter limit: (query)  (optional, default to 50)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<PresentationListEnvelope> 
     */
    open class func listPresentationsWithRequestBuilder(accountId: String? = nil, provider: String? = nil, xWorkspaceID: String? = nil, limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PresentationListEnvelope> {
        let localVariablePath = "/v1/slides"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
            "provider": (wrappedValue: provider?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PresentationListEnvelope>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List the canvas elements on a slide.
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SlideElementList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listSlideElements(id: String, slideId: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SlideElementList {
        return try await listSlideElementsWithRequestBuilder(id: id, slideId: slideId, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     List the canvas elements on a slide.
     - GET /v1/slides/{id}/slides/{slideId}/elements
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SlideElementList> 
     */
    open class func listSlideElementsWithRequestBuilder(id: String, slideId: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SlideElementList> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}/elements"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SlideElementList>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List slides in a presentation.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SlideList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listSlidesInPresentation(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SlideList {
        return try await listSlidesInPresentationWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     List slides in a presentation.
     - GET /v1/slides/{id}/slides
     - Single-account list. Returns slides in the order set by their `position` field. 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SlideList> 
     */
    open class func listSlidesInPresentationWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SlideList> {
        var localVariablePath = "/v1/slides/{id}/slides"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SlideList>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Rotate the share token, invalidating outstanding URLs.
     
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: ShareSettings
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func rotatePresentationShareToken(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> ShareSettings {
        return try await rotatePresentationShareTokenWithRequestBuilder(id: id, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Rotate the share token, invalidating outstanding URLs.
     - POST /v1/slides/{id}/share/rotate
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<ShareSettings> 
     */
    open class func rotatePresentationShareTokenWithRequestBuilder(id: String, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<ShareSettings> {
        var localVariablePath = "/v1/slides/{id}/share/rotate"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ShareSettings>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update presentation metadata (partial).
     
     - parameter id: (path) Presentation id. 
     - parameter updatePresentationRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Presentation
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updatePresentation(id: String, updatePresentationRequest: UpdatePresentationRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Presentation {
        return try await updatePresentationWithRequestBuilder(id: id, updatePresentationRequest: updatePresentationRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Update presentation metadata (partial).
     - PATCH /v1/slides/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter updatePresentationRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Presentation> 
     */
    open class func updatePresentationWithRequestBuilder(id: String, updatePresentationRequest: UpdatePresentationRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Presentation> {
        var localVariablePath = "/v1/slides/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updatePresentationRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Presentation>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a slide (partial).
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter updateSlideRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: Slide
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateSlide(id: String, slideId: String, updateSlideRequest: UpdateSlideRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> Slide {
        return try await updateSlideWithRequestBuilder(id: id, slideId: slideId, updateSlideRequest: updateSlideRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Update a slide (partial).
     - PATCH /v1/slides/{id}/slides/{slideId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter updateSlideRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<Slide> 
     */
    open class func updateSlideWithRequestBuilder(id: String, slideId: String, updateSlideRequest: UpdateSlideRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<Slide> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateSlideRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Slide>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update a slide element (partial).
     
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter elementId: (path) Slide-element id. 
     - parameter updateSlideElementRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: SlideElement
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateSlideElement(id: String, slideId: String, elementId: String, updateSlideElementRequest: UpdateSlideElementRequest, accountId: String? = nil, xWorkspaceID: String? = nil) async throws -> SlideElement {
        return try await updateSlideElementWithRequestBuilder(id: id, slideId: slideId, elementId: elementId, updateSlideElementRequest: updateSlideElementRequest, accountId: accountId, xWorkspaceID: xWorkspaceID).execute().body
    }

    /**
     Update a slide element (partial).
     - PATCH /v1/slides/{id}/slides/{slideId}/elements/{elementId}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path) Presentation id. 
     - parameter slideId: (path) Slide id within the presentation. 
     - parameter elementId: (path) Slide-element id. 
     - parameter updateSlideElementRequest: (body)  
     - parameter accountId: (query) Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account.  (optional)
     - parameter xWorkspaceID: (header) Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly.  (optional)
     - returns: RequestBuilder<SlideElement> 
     */
    open class func updateSlideElementWithRequestBuilder(id: String, slideId: String, elementId: String, updateSlideElementRequest: UpdateSlideElementRequest, accountId: String? = nil, xWorkspaceID: String? = nil) -> RequestBuilder<SlideElement> {
        var localVariablePath = "/v1/slides/{id}/slides/{slideId}/elements/{elementId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let slideIdPreEscape = "\(APIHelper.mapValueToPathItem(slideId))"
        let slideIdPostEscape = slideIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slideId}", with: slideIdPostEscape, options: .literal, range: nil)
        let elementIdPreEscape = "\(APIHelper.mapValueToPathItem(elementId))"
        let elementIdPostEscape = elementIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{elementId}", with: elementIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateSlideElementRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "accountId": (wrappedValue: accountId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Workspace-ID": xWorkspaceID?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SlideElement>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
