//
// TerminalAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TerminalAPI {

    /**
     Create a terminal session record. PTY bytes flow renderer ↔ local-agent over IPC and never traverse this API. 
     
     - parameter requestBody: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createTerminalSession(requestBody: [String: AnyCodable]) async throws -> [String: AnyCodable] {
        return try await createTerminalSessionWithRequestBuilder(requestBody: requestBody).execute().body
    }

    /**
     Create a terminal session record. PTY bytes flow renderer ↔ local-agent over IPC and never traverse this API. 
     - POST /v1/terminal/sessions
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter requestBody: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func createTerminalSessionWithRequestBuilder(requestBody: [String: AnyCodable]) -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/v1/terminal/sessions"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete a terminal session record.
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteTerminalSession(id: String) async throws {
        return try await deleteTerminalSessionWithRequestBuilder(id: id).execute().body
    }

    /**
     Delete a terminal session record.
     - DELETE /v1/terminal/sessions/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteTerminalSessionWithRequestBuilder(id: String) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/terminal/sessions/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SpatioAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Fetch a terminal session.
     
     - parameter id: (path)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getTerminalSession(id: String) async throws -> [String: AnyCodable] {
        return try await getTerminalSessionWithRequestBuilder(id: id).execute().body
    }

    /**
     Fetch a terminal session.
     - GET /v1/terminal/sessions/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func getTerminalSessionWithRequestBuilder(id: String) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/terminal/sessions/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List the caller's terminal sessions (metadata only — no PTY bytes).
     
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listTerminalSessions() async throws -> [String: AnyCodable] {
        return try await listTerminalSessionsWithRequestBuilder().execute().body
    }

    /**
     List the caller's terminal sessions (metadata only — no PTY bytes).
     - GET /v1/terminal/sessions
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func listTerminalSessionsWithRequestBuilder() -> RequestBuilder<[String: AnyCodable]> {
        let localVariablePath = "/v1/terminal/sessions"
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update terminal session metadata (title, cwd, etc.).
     
     - parameter id: (path)  
     - parameter requestBody: (body)  
     - returns: [String: AnyCodable]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateTerminalSession(id: String, requestBody: [String: AnyCodable]) async throws -> [String: AnyCodable] {
        return try await updateTerminalSessionWithRequestBuilder(id: id, requestBody: requestBody).execute().body
    }

    /**
     Update terminal session metadata (title, cwd, etc.).
     - PATCH /v1/terminal/sessions/{id}
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter id: (path)  
     - parameter requestBody: (body)  
     - returns: RequestBuilder<[String: AnyCodable]> 
     */
    open class func updateTerminalSessionWithRequestBuilder(id: String, requestBody: [String: AnyCodable]) -> RequestBuilder<[String: AnyCodable]> {
        var localVariablePath = "/v1/terminal/sessions/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SpatioAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[String: AnyCodable]>.Type = SpatioAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
